package detection

var defaultRules = []YaraRule{
	initYaraRule("EICAR_Test", "any",
		stringPat("X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*", true),
	),
	initYaraRule("Suspicious_PowerShell", "any",
		stringPat("-enc", false),
		stringPat("-e ", false),
		stringPat("Invoke-Expression", false),
		stringPat("IEX", false),
		stringPat("DownloadString", false),
		stringPat("FromBase64String", false),
		stringPat("Start-Process -WindowStyle Hidden", false),
	),
	initYaraRule("Suspicious_CMD", "any",
		stringPat("powershell -w hidden", false),
		stringPat("cmd.exe /c", false),
		stringPat("regsvr32 /s", false),
		stringPat("rundll32.exe", false),
	),
	initYaraRule("Base64_Encoded_Strings", "any",
		stringPat("TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAA", false),
	),
	initYaraRule("Suspicious_Entropy", "any",
	),
	initYaraRule("Packed_Binary", "any",
		sectionPat("UPX"),
		sectionPat("UPX0"),
		sectionPat("UPX1"),
		sectionPat(".packed"),
		sectionPat(".RLPack"),
	),
	initYaraRule("Suspicious_Imports", "any",
		importPat("CreateRemoteThread"),
		importPat("VirtualAllocEx"),
		importPat("WriteProcessMemory"),
		importPat("SetWindowsHookEx"),
	),
	initYaraRule("Process_Injection_API", "any",
		importPat("VirtualAllocEx"),
		importPat("WriteProcessMemory"),
		importPat("CreateRemoteThread"),
		importPat("ResumeThread"),
		importPat("NtUnmapViewOfSection"),
	),
	initYaraRule("Keylogger_Indicators", "any",
		importPat("SetWindowsHookEx"),
		importPat("GetAsyncKeyState"),
		importPat("GetForegroundWindow"),
		importPat("GetWindowText"),
	),
	initYaraRule("Ransomware_Indicators", "any",
		importPat("CryptEncrypt"),
		importPat("CryptDecrypt"),
		importPat("BCryptEncrypt"),
	),
	initYaraRule("VM_Escape_Indicators", "any",
		sectionPat(".vmp"),
		sectionPat(".themida"),
	),
	initYaraRule("JavaScript_Obfuscation", "any",
		stringPat("eval(", false),
		stringPat("unescape(", false),
		stringPat("fromCharCode(", false),
		stringPat("document.write(unescape", false),
	),
	initYaraRule("Suspicious_URL_Strings", "any",
		stringPat("http://", false),
		stringPat("https://", false),
		stringPat(".exe", false),
		stringPat(".dll", false),
	),
	initYaraRule("Mimikatz_Strings", "any",
		stringPat("mimikatz", false),
		stringPat("sekurlsa", false),
		stringPat("logonpasswords", false),
		stringPat("privilege::debug", false),
	),
	initYaraRule("CobaltStrike_Beacon", "any",
		sectionPat(".text"),
		importPat("InternetOpenA"),
		importPat("InternetConnectA"),
		importPat("HttpOpenRequestA"),
		importPat("HttpSendRequestA"),
		importPat("InternetReadFile"),
	),
}
