package siem

import "time"

func loadWazuhRules() []CompiledRule {
	return []CompiledRule{
		{
			RuleID:      "WAZUH_501",
			Description: "New wazuh agent connected.",
			Severity:    3,
			condition:   "field:message ~= (?i)Agent started",
		},
		{
			RuleID:      "WAZUH_502",
			Description: "Wazuh server started.",
			Severity:    3,
			condition:   "field:message ~= (?i)Manager started",
		},
		{
			RuleID:      "WAZUH_503",
			Description: "Wazuh agent started.",
			Severity:    3,
			condition:   "field:message ~= (?i)Agent started",
		},
		{
			RuleID:      "WAZUH_504",
			Description: "Wazuh agent disconnected.",
			Severity:    3,
			MITRE:       "T1562.001",
			condition:   "field:message ~= (?i)Agent disconnected",
		},
		{
			RuleID:      "WAZUH_505",
			Description: "Wazuh agent removed.",
			Severity:    3,
			MITRE:       "T1562.001",
			condition:   "field:message ~= (?i)Agent removed",
		},
		{
			RuleID:      "WAZUH_506",
			Description: "Wazuh agent stopped.",
			Severity:    3,
			MITRE:       "T1562.001",
			condition:   "field:message ~= (?i)Agent stopped",
		},
		{
			RuleID:      "WAZUH_512",
			Description: "Windows Audit event.",
			Severity:    3,
			condition:   "field:message ~= ^Windows Audit",
		},
		{
			RuleID:      "WAZUH_513",
			Description: "Windows malware detected.",
			Severity:    9,
			condition:   "field:message ~= ^Windows Malware",
		},
		{
			RuleID:      "WAZUH_516",
			Description: "System Audit event.",
			Severity:    3,
			condition:   "field:message ~= ^System Audit",
		},
		{
			RuleID:      "WAZUH_517",
			Description: "Syscheck Audit: $(extra_data)",
			Severity:    7,
			condition:   "field:message ~= ^ossec: Audit:",
		},
		{
			RuleID:      "WAZUH_518",
			Description: "Windows Adware/Spyware application found.",
			Severity:    9,
			MITRE:       "T1072",
			condition:   "field:message ~= (?i)Adware\\|Spyware",
		},
		{
			RuleID:      "WAZUH_519",
			Description: "System Audit: Vulnerable web application found.",
			Severity:    7,
			condition:   "field:message ~= ^System Audit: Web vulnerability",
		},
		{
			RuleID:      "WAZUH_520",
			Description: "Trying to add an agent with duplicate IP.",
			Severity:    3,
			condition:   "field:message ~= (?i)Duplicate IP",
		},
		{
			RuleID:      "WAZUH_521",
			Description: "Possible kernel level rootkit",
			Severity:    11,
			MITRE:       "T1014",
			condition:   "field:message ~= (?i)Possible kernel level rootkit",
		},
		{
			RuleID:      "WAZUH_531",
			Description: "Partition usage reached 100% (disk space monitor).",
			Severity:    7,
			condition:   "field:message ~= (?i)ossec: output: 'df -P': /dev/",
		},
		{
			RuleID:      "WAZUH_533",
			Description: "Listened ports status (netstat) changed (new port opened or closed).",
			Severity:    7,
			condition:   "field:message ~= (?i)ossec: output: 'netstat listening ports",
		},
		{
			RuleID:      "WAZUH_555",
			Description: "Integrity checksum for agentless device changed.",
			Severity:    7,
			condition:   "field:message ~= ^ossec: agentless: ",
		},
		{
			RuleID:      "WAZUH_560",
			Description: "FIM real-time queue is full. Some real-time events may be lost.",
			Severity:    7,
			condition:   "field:message ~= ^ossec: Real-time inotify kernel queue is full.",
		},
		{
			RuleID:      "WAZUH_591",
			Description: "Log file rotated.",
			Severity:    3,
			condition:   "field:message ~= ^ossec: File rotated ",
		},
		{
			RuleID:      "WAZUH_592",
			Description: "Log file size reduced.",
			Severity:    8,
			MITRE:       "T1565.001",
			condition:   "field:message ~= ^ossec: File size reduced",
		},
		{
			RuleID:      "WAZUH_593",
			Description: "Microsoft Event log cleared.",
			Severity:    9,
			MITRE:       "T1070",
			condition:   "field:message ~= ^ossec: Event log cleared",
		},
		{
			RuleID:      "WAZUH_220",
			Description: "The agent could not restart due to a $(module) failure in the remote configuration",
			Severity:    7,
			condition:   "field:message ~= ^wazuh: Invalid remote configuration: ",
		},
		{
			RuleID:      "WAZUH_222",
			Description: "The agent could not restart due to a error while unmerging files.",
			Severity:    7,
			condition:   "field:message ~= ^wazuh: Could not unmerge shared file.",
		},
		{
			RuleID:      "WAZUH_428",
			Description: "Wazuh API: Warning event - IP: $(srcip) blocked due to exceeded loging attemps.",
			Severity:    10,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)IP blocked due to exceeded number of logins attempts",
		},
		{
			RuleID:      "WAZUH_3102",
			Description: "MX record (Requested action aborted).",
			Severity:    5,
			MITRE:       "T1114",
			condition:   "field:message ~= (?i)reject=451 4\\.1\\.8 ",
		},
		{
			RuleID:      "WAZUH_3103",
			Description: "(55x: Requested action not taken).",
			Severity:    6,
			MITRE:       "T1114",
			condition:   "field:message ~= (?i)reject=550 5\\.0\\.0 \\|reject=553 5\\.3\\.0",
		},
		{
			RuleID:      "WAZUH_3104",
			Description: "(550: Requested action not taken).",
			Severity:    6,
			MITRE:       "T1114",
			condition:   "field:message ~= (?i)reject=550 5\\.7\\.1 ",
		},
		{
			RuleID:      "WAZUH_3105",
			Description: "(553: Requested action not taken).",
			Severity:    5,
			MITRE:       "T1114",
			condition:   "field:message ~= (?i)reject=553 5\\.1\\.8 ",
		},
		{
			RuleID:      "WAZUH_3106",
			Description: "(553: Requested action not taken).",
			Severity:    5,
			MITRE:       "T1114",
			condition:   "field:message ~= (?i)reject=553 5\\.5\\.4 ",
		},
		{
			RuleID:      "WAZUH_3108",
			Description: "sendmail: Sendmail rejected due to pre-greeting.",
			Severity:    6,
			MITRE:       "T1114",
			condition:   "field:message ~= (?i)rejecting commands from",
		},
		{
			RuleID:      "WAZUH_3109",
			Description: "sendmail: Sendmail save mail panic.",
			Severity:    8,
			condition:   "field:message ~= (?i)savemail panic",
		},
		{
			RuleID:      "WAZUH_3191",
			Description: "address (REJECTED).",
			Severity:    6,
			MITRE:       "T1114",
			condition:   "field:message ~= ^sender check failed|^sender check tempfailed",
		},
		{
			RuleID:      "WAZUH_3901",
			Description: "New courier (imap/pop3) connection.",
			Severity:    3,
			condition:   "field:message ~= ^Connection, ",
		},
		{
			RuleID:      "WAZUH_3902",
			Description: "Courier (imap/pop3) authentication failed.",
			Severity:    5,
			condition:   "field:message ~= ^LOGIN FAILED,| FAILED:",
		},
		{
			RuleID:      "WAZUH_3904",
			Description: "Courier (imap/pop3) authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= ^LOGIN,",
		},
		{
			RuleID:      "WAZUH_4338",
			Description: "PIX: Firewall failover pair communication problem.",
			Severity:    8,
			condition:   "field:message ~= (?i)Failed\\|Lost Failover",
		},
		{
			RuleID:      "WAZUH_4560",
			Description: "netscreen detected a SYN flood.",
			Severity:    3,
			condition:   "field:message ~= (?i)SYN flood! ",
		},
		{
			RuleID:      "WAZUH_5501",
			Description: "PAM: Login session opened.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)session opened for user ",
		},
		{
			RuleID:      "WAZUH_5502",
			Description: "PAM: Login session closed.",
			Severity:    3,
			condition:   "field:message ~= (?i)session closed for user ",
		},
		{
			RuleID:      "WAZUH_5503",
			Description: "PAM: User login failed.",
			Severity:    5,
			MITRE:       "T1110.001",
			condition:   "field:message ~= (?i)authentication failure; logname=",
		},
		{
			RuleID:      "WAZUH_5504",
			Description: "PAM: Attempt to login with an invalid user.",
			Severity:    5,
			condition:   "field:message ~= (?i)check pass; user unknown",
		},
		{
			RuleID:      "WAZUH_5553",
			Description: "PAM misconfiguration.",
			Severity:    4,
			condition:   "field:message ~= (?i)cannot open shared object file: No such file or directory",
		},
		{
			RuleID:      "WAZUH_5554",
			Description: "PAM misconfiguration.",
			Severity:    4,
			condition:   "field:message ~= (?i)illegal module type: ",
		},
		{
			RuleID:      "WAZUH_5555",
			Description: "PAM: User changed password.",
			Severity:    3,
			condition:   "field:message ~= (?i): password changed for",
		},
		{
			RuleID:      "WAZUH_5557",
			Description: "unix_chkpwd: Password check failed.",
			Severity:    5,
			MITRE:       "T1110.001",
			condition:   "field:message ~= (?i)password check failed ",
		},
		{
			RuleID:      "WAZUH_5601",
			Description: "telnetd: Connection refused by TCP Wrappers.",
			Severity:    5,
			MITRE:       "T1095",
			condition:   "field:message ~= (?i)refused connect from ",
		},
		{
			RuleID:      "WAZUH_5602",
			Description: "telnetd: Remote host established a telnet connection.",
			Severity:    3,
			condition:   "field:message ~= (?i)connect from ",
		},
		{
			RuleID:      "WAZUH_5603",
			Description: "telnetd: Remote host invalid connection.",
			Severity:    5,
			condition:   "field:message ~= (?i)ttloop:  peer died:\\|ttloop:  read:",
			windowDur:   1 * time.Second,
		},
		{
			RuleID:      "WAZUH_5604",
			Description: "telnetd: Reverse lookup error (bad hostname config).",
			Severity:    5,
			condition:   "field:message ~= (?i)warning: can't verify hostname:",
		},
		{
			RuleID:      "WAZUH_5701",
			Description: "sshd: Possible attack on the ssh server (or version gathering).",
			Severity:    8,
			MITRE:       "T1190",
			condition:   "field:message ~= (?i)Bad protocol version identification",
		},
		{
			RuleID:      "WAZUH_5702",
			Description: "sshd: Reverse lookup error (bad ISP or attack).",
			Severity:    5,
			condition:   "field:message ~= ^reverse mapping",
		},
		{
			RuleID:      "WAZUH_5704",
			Description: "sshd: Timeout while logging in.",
			Severity:    4,
			condition:   "field:message ~= (?i)fatal: Timeout before authentication for",
		},
		{
			RuleID:      "WAZUH_5706",
			Description: "sshd: insecure connection attempt (scan).",
			Severity:    6,
			MITRE:       "T1021.004",
			condition:   "field:message ~= (?i)Did not receive identification string from",
		},
		{
			RuleID:      "WAZUH_5707",
			Description: "sshd: OpenSSH challenge-response exploit.",
			Severity:    14,
			MITRE:       "T1210,T1068",
			condition:   "field:message ~= (?i)fatal: buffer_get_string: bad string",
		},
		{
			RuleID:      "WAZUH_5710",
			Description: "sshd: Attempt to login using a non-existent user",
			Severity:    5,
			MITRE:       "T1110.001,T1021.004",
			condition:   "field:message ~= (?i)illegal user\\|invalid user",
		},
		{
			RuleID:      "WAZUH_5713",
			Description: "sshd: Corrupted bytes on SSHD.",
			Severity:    6,
			condition:   "field:message ~= (?i)Corrupted check bytes on",
		},
		{
			RuleID:      "WAZUH_5714",
			Description: "sshd: SSH CRC-32 Compensation attack",
			Severity:    14,
			MITRE:       "T1210",
			condition:   "field:message ~= (?i)Local: crc32 compensation attack",
			threshold:   3,
			windowDur:   120 * time.Second,
		},
		{
			RuleID:      "WAZUH_5715",
			Description: "sshd: authentication success.",
			Severity:    3,
			MITRE:       "T1078,T1021",
			condition:   "field:message ~= ^Accepted|authenticated.$",
		},
		{
			RuleID:      "WAZUH_5716",
			Description: "sshd: authentication failed.",
			Severity:    5,
			MITRE:       "T1110",
			condition:   "field:message ~= ^Failed|^error: PAM: Authentication",
		},
		{
			RuleID:      "WAZUH_5717",
			Description: "sshd: configuration error (moduli).",
			Severity:    4,
			condition:   "field:message ~= (?i)error: Bad prime description in line",
		},
		{
			RuleID:      "WAZUH_5718",
			Description: "sshd: Attempt to login using a denied user.",
			Severity:    5,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)not allowed because",
		},
		{
			RuleID:      "WAZUH_5726",
			Description: "sshd: Unknown PAM module, PAM misconfiguration.",
			Severity:    5,
			condition:   "field:message ~= (?i)error: PAM: Module is unknown for",
		},
		{
			RuleID:      "WAZUH_5728",
			Description: "sshd: Authentication services were not able to retrieve user credentials.",
			Severity:    4,
			condition:   "field:message ~= (?i)Authentication service cannot retrieve user credentials",
		},
		{
			RuleID:      "WAZUH_5730",
			Description: "sshd: SSHD is not accepting connections.",
			Severity:    4,
			condition:   "field:message ~= error: connect to \\S+ port \\d+ failed: Connection refused",
		},
		{
			RuleID:      "WAZUH_5731",
			Description: "sshd: SSH Scanning.",
			Severity:    6,
			MITRE:       "T1046",
			condition:   "field:message ~= (?i)AKASSH_Version_Mapper1\\.",
		},
		{
			RuleID:      "WAZUH_5737",
			Description: "sshd: cannot bind to configured address.",
			Severity:    5,
			condition:   "field:message ~= ^fatal: Cannot bind any address.$",
		},
		{
			RuleID:      "WAZUH_5738",
			Description: "sshd: pam_loginuid could not open loginuid.",
			Severity:    5,
			condition:   "field:message ~= (?i)set_loginuid failed opening loginuid\\$",
		},
		{
			RuleID:      "WAZUH_5739",
			Description: "sshd: configuration error (AuthorizedKeysCommand)",
			Severity:    4,
			condition:   "field:message ~= ^error: Could not stat AuthorizedKeysCommand",
		},
		{
			RuleID:      "WAZUH_5740",
			Description: "sshd: connection reset by peer",
			Severity:    4,
			condition:   "field:message ~= (?i)Connection reset by peer\\$",
		},
		{
			RuleID:      "WAZUH_5741",
			Description: "sshd: connection refused",
			Severity:    4,
			condition:   "field:message ~= (?i)Connection refused\\$",
		},
		{
			RuleID:      "WAZUH_5742",
			Description: "sshd: connection timed out",
			Severity:    4,
			condition:   "field:message ~= (?i)Connection timed out\\$",
		},
		{
			RuleID:      "WAZUH_5743",
			Description: "sshd: no route to host",
			Severity:    4,
			condition:   "field:message ~= (?i)No route to host\\$",
		},
		{
			RuleID:      "WAZUH_5744",
			Description: "sshd: port forwarding issue",
			Severity:    4,
			condition:   "field:message ~= (?i)failure direct-tcpip\\$",
		},
		{
			RuleID:      "WAZUH_5745",
			Description: "sshd: transport endpoint is not connected",
			Severity:    4,
			condition:   "field:message ~= (?i)Transport endpoint is not connected\\$",
		},
		{
			RuleID:      "WAZUH_5746",
			Description: "sshd: get_remote_port failed",
			Severity:    4,
			condition:   "field:message ~= (?i)get_remote_port failed\\$",
		},
		{
			RuleID:      "WAZUH_5747",
			Description: "sshd: bad client public DH value",
			Severity:    6,
			condition:   "field:message ~= (?i)bad client public DH value",
		},
		{
			RuleID:      "WAZUH_5748",
			Description: "sshd: corrupted MAC on input",
			Severity:    6,
			condition:   "field:message ~= (?i)Corrupted MAC on input\\.",
		},
		{
			RuleID:      "WAZUH_5749",
			Description: "sshd: bad packet length",
			Severity:    4,
			condition:   "field:message ~= ^Bad packet length",
		},
		{
			RuleID:      "WAZUH_5755",
			Description: "sshd: Authentication refused due to owner/permissions of authorized_keys.",
			Severity:    3,
			condition:   "field:message ~= (?i)bad ownership or modes for file",
		},
		{
			RuleID:      "WAZUH_5758",
			Description: "Maximum authentication attempts exceeded.",
			Severity:    8,
			MITRE:       "T1110",
			condition:   "field:message ~= ^error: maximum authentication attempts exceeded ",
		},
		{
			RuleID:      "WAZUH_5760",
			Description: "sshd: authentication failed.",
			Severity:    5,
			MITRE:       "T1110.001,T1021.004",
			condition:   "field:message ~= (?i)Failed password\\|Failed keyboard\\|authentication error",
		},
		{
			RuleID:      "WAZUH_5762",
			Description: "sshd: connection reset",
			Severity:    4,
			condition:   "field:message ~= (?i)Connection reset",
		},
		{
			RuleID:      "WAZUH_6103",
			Description: "Solaris: Login session succeeded.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= ^login",
		},
		{
			RuleID:      "WAZUH_6104",
			Description: "Solaris: Login session failed.",
			Severity:    5,
			condition:   "field:message ~= ^login",
		},
		{
			RuleID:      "WAZUH_6105",
			Description: "Solaris: User successfully changed UID.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= ^su ",
		},
		{
			RuleID:      "WAZUH_6106",
			Description: "Solaris: User failed to change UID (user id).",
			Severity:    5,
			condition:   "field:message ~= ^su ",
		},
		{
			RuleID:      "WAZUH_6202",
			Description: "Asterisk warning message.",
			Severity:    3,
			condition:   "field:message ~= ^WARN",
		},
		{
			RuleID:      "WAZUH_6203",
			Description: "Asterisk error message.",
			Severity:    3,
			condition:   "field:message ~= ^ERROR",
		},
		{
			RuleID:      "WAZUH_6210",
			Description: "Asterisk: Login session failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)Wrong password",
		},
		{
			RuleID:      "WAZUH_6211",
			Description: "Asterisk: Login session failed (invalid user).",
			Severity:    5,
			condition:   "field:message ~= (?i)Username/auth name mismatch",
		},
		{
			RuleID:      "WAZUH_6212",
			Description: "Asterisk: Login session failed (invalid extension).",
			Severity:    5,
			condition:   "field:message ~= (?i)No matching peer found",
		},
		{
			RuleID:      "WAZUH_6253",
			Description: "Asterisk: Login session failed (invalid iax user).",
			Severity:    5,
			condition:   "field:message ~= (?i)No registration for peer",
		},
		{
			RuleID:      "WAZUH_6255",
			Description: "Asterisk: Possible Registration Hijacking.",
			Severity:    5,
			condition:   "field:message ~= (?i)Don't know how to respond via",
		},
		{
			RuleID:      "WAZUH_6256",
			Description: "Asterisk: IAX peer Wrong Password.",
			Severity:    5,
			condition:   "field:message ~= (?i)failed MD5 authentication",
		},
		{
			RuleID:      "WAZUH_7202",
			Description: "Arpwatch: \"flip flop\" message. IP address/MAC relation changing too often.",
			Severity:    9,
			condition:   "field:message ~= (?i)flip flop ",
		},
		{
			RuleID:      "WAZUH_7203",
			Description: "Arpwatch: exiting.",
			Severity:    3,
			condition:   "field:message ~= (?i)reaper: pid ",
		},
		{
			RuleID:      "WAZUH_7204",
			Description: "Arpwatch: Changed network interface for ip address.",
			Severity:    9,
			condition:   "field:message ~= (?i)changed ethernet address ",
		},
		{
			RuleID:      "WAZUH_7209",
			Description: "Arpwatch: Possible arpspoofing attempt.",
			Severity:    7,
			MITRE:       "T1095",
			condition:   "field:message ~= (?i)ethernet mismatch",
		},
		{
			RuleID:      "WAZUH_9302",
			Description: "Horde IMP notice message.",
			Severity:    3,
			condition:   "field:message ~= ^[notice]",
		},
		{
			RuleID:      "WAZUH_9303",
			Description: "Horde IMP error message.",
			Severity:    5,
			condition:   "field:message ~= ^[error]",
		},
		{
			RuleID:      "WAZUH_9304",
			Description: "Horde IMP emergency message.",
			Severity:    9,
			condition:   "field:message ~= ^[emergency]",
		},
		{
			RuleID:      "WAZUH_9305",
			Description: "Horde IMP successful login.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Login success for ",
		},
		{
			RuleID:      "WAZUH_9306",
			Description: "Horde IMP Failed login.",
			Severity:    5,
			condition:   "field:message ~= (?i)FAILED LOGIN ",
		},
		{
			RuleID:      "WAZUH_9401",
			Description: "Roundcube authentication failed.",
			Severity:    6,
			condition:   "field:message ~= (?i)failed \\(LOGIN\\)\\| Login failed \\| Authentication failed\\| Failed login ",
		},
		{
			RuleID:      "WAZUH_9402",
			Description: "Roundcube authentication succeeded.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Successful login",
		},
		{
			RuleID:      "WAZUH_9501",
			Description: "Wordpress authentication failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)User authentication failed",
		},
		{
			RuleID:      "WAZUH_9502",
			Description: "Wordpress authentication succeeded.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)User logged in",
		},
		{
			RuleID:      "WAZUH_9503",
			Description: "WPsyslog was successfully initialized.",
			Severity:    3,
			condition:   "field:message ~= (?i)WPsyslog was successfully initiali",
		},
		{
			RuleID:      "WAZUH_9504",
			Description: "Wordpress plugin deactivated.",
			Severity:    3,
			condition:   "field:message ~= (?i)Plugin deactivated",
		},
		{
			RuleID:      "WAZUH_9505",
			Description: "Wordpress Comment Flood Attempt.",
			Severity:    7,
			MITRE:       "T1499",
			condition:   "field:message ~= (?i)Warning: Comment flood attempt",
		},
		{
			RuleID:      "WAZUH_9510",
			Description: "Attack against Wordpress detected.",
			Severity:    7,
			condition:   "field:message ~= (?i)Warning: IDS:",
		},
		{
			RuleID:      "WAZUH_9610",
			Description: "cimserver: Compaq Insight Manager authentication failure.",
			Severity:    5,
			condition:   "field:message ~= (?i)Authentication failed",
		},
		{
			RuleID:      "WAZUH_9611",
			Description: "cimserver: Compaq Insight Manager stopped.",
			Severity:    12,
			MITRE:       "T1499",
			condition:   "field:message ~= (?i)Server stopped",
		},
		{
			RuleID:      "WAZUH_9701",
			Description: "Dovecot Authentication Success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)login: Login: ",
		},
		{
			RuleID:      "WAZUH_9702",
			Description: "Dovecot Authentication Failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)Password mismatch\\$",
		},
		{
			RuleID:      "WAZUH_9703",
			Description: "Dovecot is Starting Up.",
			Severity:    3,
			condition:   "field:message ~= (?i)starting up",
		},
		{
			RuleID:      "WAZUH_9705",
			Description: "Dovecot Invalid User Login Attempt.",
			Severity:    5,
			condition:   "field:message ~= (?i)user not found\\|User not known\\|unknown user\\|auth failed",
		},
		{
			RuleID:      "WAZUH_9706",
			Description: "Dovecot Session Disconnected.",
			Severity:    3,
			condition:   "field:message ~= (?i): Disconnected: ",
		},
		{
			RuleID:      "WAZUH_9707",
			Description: "Dovecot Aborted Login.",
			Severity:    5,
			condition:   "field:message ~= (?i): Aborted login",
		},
		{
			RuleID:      "WAZUH_9771",
			Description: "Dovecot Invalid User Login Attempt.",
			Severity:    5,
			condition:   "field:message ~= (?i)user not found\\|User not known\\|unknown user\\|auth failed",
		},
		{
			RuleID:      "WAZUH_9801",
			Description: "vm-pop3d: Login failed accessing the pop3 server.",
			Severity:    5,
			condition:   "field:message ~= (?i)failed auth",
		},
		{
			RuleID:      "WAZUH_9901",
			Description: "vpopmail: Login failed.",
			Severity:    5,
			condition:   "field:message ~= (?i) password fail ",
		},
		{
			RuleID:      "WAZUH_9902",
			Description: "vpopmail: Attempt to login to vpopmail with invalid username.",
			Severity:    5,
			condition:   "field:message ~= (?i) vpopmail user not found ",
		},
		{
			RuleID:      "WAZUH_9903",
			Description: "vpopmail: Attempt to login to vpopmail with empty password.",
			Severity:    5,
			condition:   "field:message ~= (?i) null password given ",
		},
		{
			RuleID:      "WAZUH_9904",
			Description: "vpopmail: successful login.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i) login success ",
		},
		{
			RuleID:      "WAZUH_11101",
			Description: "FTPD: connection refused.",
			Severity:    5,
			condition:   "field:message ~= (?i)FTP LOGIN REFUSED",
		},
		{
			RuleID:      "WAZUH_11106",
			Description: "FTPD: Remote host connected to FTP server.,",
			Severity:    3,
			condition:   "field:message ~= (?i)FTP LOGIN FROM\\|connection from\\|connect from",
		},
		{
			RuleID:      "WAZUH_11107",
			Description: "FTPD: Connection blocked by Tcp Wrappers.",
			Severity:    5,
			MITRE:       "T1095",
			condition:   "field:message ~= (?i)refused connect from",
		},
		{
			RuleID:      "WAZUH_11108",
			Description: "FTPD: Reverse lookup error (bad ISP config).",
			Severity:    5,
			condition:   "field:message ~= (?i)warning: can't verify hostname: \\|gethostbyaddr: ",
		},
		{
			RuleID:      "WAZUH_11109",
			Description: "FTPD: Multiple FTP failed login attempts.",
			Severity:    10,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)repeated login failures",
		},
		{
			RuleID:      "WAZUH_11110",
			Description: "FTPD: User disconnected due to time out.",
			Severity:    3,
			condition:   "field:message ~= (?i)timed out after",
		},
		{
			RuleID:      "WAZUH_11111",
			Description: "FTPD: Attempt to login with disabled account.",
			Severity:    9,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)PAM_ERROR_MSG: Account is disabled",
		},
		{
			RuleID:      "WAZUH_11112",
			Description: "FTPD: authentication failure.",
			Severity:    5,
			condition:   "field:message ~= ^Failed authentication from",
		},
		{
			RuleID:      "WAZUH_11113",
			Description: "FTPD: authentication failure.",
			Severity:    5,
			condition:   "field:message ~= ^login \\S+ from \\S+ failed",
		},
		{
			RuleID:      "WAZUH_11201",
			Description: "ProFTPD: FTP session opened.",
			Severity:    3,
			condition:   "field:message ~= (?i)FTP session opened\\.\\$",
		},
		{
			RuleID:      "WAZUH_11203",
			Description: "ProFTPD: Attempt to login using a non-existent user.",
			Severity:    5,
			condition:   "field:message ~= (?i) no such user ",
		},
		{
			RuleID:      "WAZUH_11204",
			Description: "ProFTPD: Login failed accessing the FTP server.",
			Severity:    5,
			condition:   "field:message ~= (?i)Incorrect password\\.\\$\\|Login failed",
		},
		{
			RuleID:      "WAZUH_11205",
			Description: "ProFTPD: FTP Authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Login successful",
		},
		{
			RuleID:      "WAZUH_11206",
			Description: "ProFTPD: Connection denied by ProFTPD configuration.",
			Severity:    5,
			condition:   "field:message ~= Connection from \\S+ [\\S+] denied",
		},
		{
			RuleID:      "WAZUH_11207",
			Description: "ProFTPD: Connection refused by TCP Wrappers.",
			Severity:    5,
			MITRE:       "T1095",
			condition:   "field:message ~= (?i)refused connect from",
		},
		{
			RuleID:      "WAZUH_11208",
			Description: "ProFTPD: Small PassivePorts range in config file. Server misconfiguration.",
			Severity:    4,
			condition:   "field:message ~= (?i)unable to find open port in PassivePorts range",
		},
		{
			RuleID:      "WAZUH_11209",
			Description: "ProFTPD: Attempt to bypass firewall that can't adequately keep state of FTP traffic.",
			Severity:    14,
			MITRE:       "T1071",
			condition:   "field:message ~= (?i)Refused PORT ",
		},
		{
			RuleID:      "WAZUH_11210",
			Description: "ProFTPD: Multiple failed login attempts.",
			Severity:    10,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)Maximum login attempts ",
		},
		{
			RuleID:      "WAZUH_11211",
			Description: "ProFTPD: Mismatch in server's hostname.",
			Severity:    4,
			condition:   "field:message ~= (?i)host name/name mismatch\\|host name/address mismatch",
		},
		{
			RuleID:      "WAZUH_11212",
			Description: "ProFTPD: Reverse lookup error (bad ISP config).",
			Severity:    5,
			condition:   "field:message ~= (?i)warning: can't verify hostname: ",
		},
		{
			RuleID:      "WAZUH_11213",
			Description: "ProFTPD: Remote host connected to FTP server.",
			Severity:    3,
			condition:   "field:message ~= (?i)connect from ",
		},
		{
			RuleID:      "WAZUH_11214",
			Description: "ProFTPD: Remote host disconnected due to inactivity.",
			Severity:    3,
			condition:   "field:message ~= (?i)FTP no transfer timeout, disconnected",
		},
		{
			RuleID:      "WAZUH_11215",
			Description: "ProFTPD: Remote host disconnected due to login time out.",
			Severity:    3,
			condition:   "field:message ~= (?i)FTP login timed out, disconnected",
		},
		{
			RuleID:      "WAZUH_11216",
			Description: "ProFTPD: Remote host disconnected due to time out.",
			Severity:    3,
			condition:   "field:message ~= (?i)FTP session idle timeout, disconnected",
		},
		{
			RuleID:      "WAZUH_11217",
			Description: "ProFTPD: Data transfer stalled.",
			Severity:    3,
			condition:   "field:message ~= (?i)Data transfer stall timeout:",
		},
		{
			RuleID:      "WAZUH_11218",
			Description: "ProFTPD: FTP process crashed.",
			Severity:    12,
			MITRE:       "T1210",
			condition:   "field:message ~= (?i)ProFTPD terminating \\(signal 11\\)",
		},
		{
			RuleID:      "WAZUH_11219",
			Description: "ProFTPD: FTP server Buffer overflow attempt.",
			Severity:    12,
			MITRE:       "T1499",
			condition:   "field:message ~= (?i)Reallocating sreaddir buffer",
		},
		{
			RuleID:      "WAZUH_11220",
			Description: "ProFTPD: Unable to bind to adress.",
			Severity:    4,
			condition:   "field:message ~= (?i)listen\\(\\) failed in",
		},
		{
			RuleID:      "WAZUH_11222",
			Description: "ProFTPD: Couldn't open the incoming connection. Check log message for reason.",
			Severity:    4,
			condition:   "field:message ~= (?i)unable to open incoming connection",
		},
		{
			RuleID:      "WAZUH_11301",
			Description: "pure-ftpd: New FTP connection.",
			Severity:    3,
			condition:   "field:message ~= (?i)\\[INFO\\] New connection from",
		},
		{
			RuleID:      "WAZUH_11302",
			Description: "pure-ftpd: FTP Authentication failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)\\[WARNING\\] Authentication failed for user",
		},
		{
			RuleID:      "WAZUH_11305",
			Description: "pure-ftpd: Attempt to access invalid directory",
			Severity:    5,
			condition:   "field:message ~= (?i)\\[INFO\\] Can't change directory to",
		},
		{
			RuleID:      "WAZUH_11309",
			Description: "pure-ftpd: FTP Authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)\\[INFO\\] \\S\\+ is now logged in\\| is now logged in",
		},
		{
			RuleID:      "WAZUH_11401",
			Description: "vsftpd: FTP session opened.",
			Severity:    3,
			condition:   "field:message ~= (?i)CONNECT: Client",
		},
		{
			RuleID:      "WAZUH_11402",
			Description: "vsftpd: FTP Authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)OK LOGIN: ",
		},
		{
			RuleID:      "WAZUH_11403",
			Description: "vsftpd: Login failed accessing the FTP server.",
			Severity:    5,
			condition:   "field:message ~= (?i)FAIL LOGIN: ",
		},
		{
			RuleID:      "WAZUH_12101",
			Description: "Invalid DNS packet. Possibility of attack.",
			Severity:    12,
			MITRE:       "T1071,T1499",
			condition:   "field:message ~= (?i)dropping source port zero packet from",
		},
		{
			RuleID:      "WAZUH_12102",
			Description: "Failed attempt to perform a zone transfer.",
			Severity:    9,
			condition:   "field:message ~= (?i)denied AXFR from",
		},
		{
			RuleID:      "WAZUH_12103",
			Description: "Generally mis-configuration.",
			Severity:    4,
			condition:   "field:message ~= (?i)denied update from\\|unapproved update from",
		},
		{
			RuleID:      "WAZUH_12104",
			Description: "Log permission misconfiguration in Named.",
			Severity:    4,
			condition:   "field:message ~= (?i)unable to rename log file",
		},
		{
			RuleID:      "WAZUH_12105",
			Description: "Unexpected error while resolving domain.",
			Severity:    4,
			condition:   "field:message ~= (?i)unexpected RCODE ",
		},
		{
			RuleID:      "WAZUH_12106",
			Description: "DNS configuration error.",
			Severity:    4,
			condition:   "field:message ~= (?i)refused notify from non-master",
		},
		{
			RuleID:      "WAZUH_12108",
			Description: "Query cache denied (probably config error).",
			Severity:    5,
			condition:   "field:message ~= (?i)query \\(cache\\) denied\\|: query \\(cache\\)",
		},
		{
			RuleID:      "WAZUH_12109",
			Description: "Named fatal error. DNS service going down.",
			Severity:    12,
			condition:   "field:message ~= (?i)exiting \\(due to fatal error\\)",
		},
		{
			RuleID:      "WAZUH_12110",
			Description: "than stored.",
			Severity:    8,
			condition:   "field:message ~= \\S+ \\S ours (\\S+)",
		},
		{
			RuleID:      "WAZUH_12111",
			Description: "Unable to perform zone transfer.",
			Severity:    8,
			condition:   "field:message ~= ^transfer of \\S+ from \\S+ failed while receiving \\S+ REFUSED",
		},
		{
			RuleID:      "WAZUH_12112",
			Description: "Zone transfer error.",
			Severity:    4,
			condition:   "field:message ~= ^zone \\S+: expired",
		},
		{
			RuleID:      "WAZUH_12119",
			Description: "BIND has been started",
			Severity:    3,
			condition:   "field:message ~= (?i)starting BIND",
		},
		{
			RuleID:      "WAZUH_12125",
			Description: "BIND Configuration error.",
			Severity:    3,
			condition:   "field:message ~= (?i)reloading configuration failed: unexpected end of input",
		},
		{
			RuleID:      "WAZUH_12129",
			Description: "Zone transfer failed, unable to connect to master.",
			Severity:    4,
			condition:   "field:message ~= (?i)failed to connect: connection refused",
		},
		{
			RuleID:      "WAZUH_12133",
			Description: "Could not open configuration file, permission denied.",
			Severity:    4,
			condition:   "field:message ~= open: \\S+: permission denied$",
		},
		{
			RuleID:      "WAZUH_12134",
			Description: "Could not open configuration file, permission denied.",
			Severity:    4,
			condition:   "field:message ~= (?i)loading configuration: permission denied",
		},
		{
			RuleID:      "WAZUH_12136",
			Description: "Master appears to be down.",
			Severity:    4,
			condition:   "field:message ~= (?i)failed to connect: host unreachable",
		},
		{
			RuleID:      "WAZUH_12139",
			Description: "Bad zone transfer request.",
			Severity:    3,
			condition:   "field:message ~= client \\S+: bad zone transfer request: \\S+: non-authoritative zone \\(NOTAUTH\\)",
		},
		{
			RuleID:      "WAZUH_12144",
			Description: "Server does not have enough memory to reload the configuration.",
			Severity:    9,
			condition:   "field:message ~= (?i)reloading configuration failed: out of memory",
		},
		{
			RuleID:      "WAZUH_13102",
			Description: "Samba connection denied.",
			Severity:    5,
			condition:   "field:message ~= (?i)Denied connection from\\|Connection denied from",
		},
		{
			RuleID:      "WAZUH_13104",
			Description: "Samba: User action denied by configuration.",
			Severity:    5,
			condition:   "field:message ~= (?i)Permission denied--",
		},
		{
			RuleID:      "WAZUH_13105",
			Description: "Samba network problems (unable to connect).",
			Severity:    3,
			condition:   "field:message ~= (?i)Unable to connect to CUPS server",
		},
		{
			RuleID:      "WAZUH_13110",
			Description: "Samba: Connection was denied.",
			Severity:    3,
			condition:   "field:message ~= (?i)Connection denied from",
		},
		{
			RuleID:      "WAZUH_13111",
			Description: "Samba: Socket is not connected, write failed.",
			Severity:    3,
			condition:   "field:message ~= (?i)Socket is not connected",
		},
		{
			RuleID:      "WAZUH_13112",
			Description: "Samba: Segfault in gvfs-smb.",
			Severity:    3,
			condition:   "tag:kernel",
		},
		{
			RuleID:      "WAZUH_14120",
			Description: "racoon: VPN established.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)ISAKMP-SA established ",
		},
		{
			RuleID:      "WAZUH_7718",
			Description: "Microsoft Security Essentials - EICAR test file detected.",
			Severity:    5,
			condition:   "field:message ~= (?i)Virus:DOS/EICAR_Test_File",
		},
		{
			RuleID:      "WAZUH_19110",
			Description: "VMWare ESX authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)logged in\\$",
		},
		{
			RuleID:      "WAZUH_19111",
			Description: "VMWare ESX authentication failure.",
			Severity:    5,
			condition:   "field:message ~= (?i)Failed login attempt for",
		},
		{
			RuleID:      "WAZUH_19112",
			Description: "VMWare ESX user login.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Accepted password for\\|login from",
		},
		{
			RuleID:      "WAZUH_19113",
			Description: "VMWare ESX user authentication failure.",
			Severity:    3,
			condition:   "field:message ~= (?i)Rejected password for",
		},
		{
			RuleID:      "WAZUH_19120",
			Description: "Virtual machine state changed to OFF.",
			Severity:    8,
			MITRE:       "T1529",
			condition:   "field:message ~= (?i)-> VM_STATE_OFF",
		},
		{
			RuleID:      "WAZUH_19121",
			Description: "Virtual machine being turned ON.",
			Severity:    3,
			condition:   "field:message ~= (?i)-> VM_STATE_POWERING_ON",
		},
		{
			RuleID:      "WAZUH_19122",
			Description: "Virtual machine state changed to ON.",
			Severity:    3,
			condition:   "field:message ~= (?i)-> VM_STATE_ON",
		},
		{
			RuleID:      "WAZUH_19123",
			Description: "Virtual machine being reconfigured.",
			Severity:    5,
			condition:   "field:message ~= (?i)-> VM_STATE_RECONFIGURING",
		},
		{
			RuleID:      "WAZUH_31109",
			Description: "MSSQL Injection attempt (/ur.php, urchin.js)",
			Severity:    6,
			MITRE:       "T1190",
			condition:   "field:message ~= %2Bchar\\(\\d+\\)%2Bchar\\(\\d+\\)%2Bchar\\(\\d+\\)%2Bchar\\(\\d+\\)%2Bchar\\(\\d+\\)%2Bchar\\(\\d+\\)",
		},
		{
			RuleID:      "WAZUH_31166",
			Description: "Shellshock attack attempt",
			Severity:    6,
			MITRE:       "T1068,T1190",
			condition:   "field:message ~= \"\\(\\)\\s*{\\s*\\w*:;\\s*}\\s*;|\"\\(\\)\\s*{\\s*\\w*;\\s*}\\s*;",
		},
		{
			RuleID:      "WAZUH_31167",
			Description: "Shellshock attack attempt",
			Severity:    6,
			MITRE:       "T1068,T1190",
			condition:   "field:message ~= \"\\(\\)\\s*{\\s*_;\\.*}\\s*>_[\\$\\(\\$\\(\\)\\)]\\s*{",
		},
		{
			RuleID:      "WAZUH_31168",
			Description: "Shellshock attack detected",
			Severity:    15,
			MITRE:       "T1068,T1190",
			condition:   "field:message ~= \"\\(\\)\\s*{\\s*\\w*:;\\s*}\\s*;|\"\\(\\)\\s*{\\s*\\w*;\\s*}\\s*;",
		},
		{
			RuleID:      "WAZUH_31169",
			Description: "Shellshock attack detected",
			Severity:    15,
			MITRE:       "T1068,T1190",
			condition:   "field:message ~= \"\\(\\)\\s*{\\s*_;\\.*}\\s*>_[\\$\\(\\$\\(\\)\\)]\\s*{",
		},
		{
			RuleID:      "WAZUH_30104",
			Description: "Apache: Segmentation fault.",
			Severity:    12,
			condition:   "field:message ~= (?i)exit signal Segmentation Fault",
		},
		{
			RuleID:      "WAZUH_30105",
			Description: "Apache: Attempt to access forbidden file or directory.",
			Severity:    5,
			condition:   "field:message ~= (?i)denied by server configuration",
		},
		{
			RuleID:      "WAZUH_30106",
			Description: "Apache: Attempt to access forbidden directory index.",
			Severity:    5,
			condition:   "field:message ~= (?i)Directory index forbidden by rule",
		},
		{
			RuleID:      "WAZUH_30107",
			Description: "Apache: Code Red attack.",
			Severity:    6,
			MITRE:       "T1102",
			condition:   "field:message ~= (?i)Client sent malformed Host header",
		},
		{
			RuleID:      "WAZUH_30108",
			Description: "Apache: User authentication failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)authentication failed",
		},
		{
			RuleID:      "WAZUH_30109",
			Description: "Apache: Attempt to login using a non-existent user.",
			Severity:    9,
			condition:   "field:message ~= user \\S+ not found|user \\S+ in realm \\.* not found",
		},
		{
			RuleID:      "WAZUH_30110",
			Description: "Apache: User authentication failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)authentication failure",
		},
		{
			RuleID:      "WAZUH_30115",
			Description: "Apache: Invalid URI (bad client request).",
			Severity:    5,
			condition:   "field:message ~= (?i)Invalid URI in request",
		},
		{
			RuleID:      "WAZUH_30117",
			Description: "Apache: Invalid URI, file name too long.",
			Severity:    10,
			condition:   "field:message ~= (?i)File name too long\\|request failed: URI too long",
		},
		{
			RuleID:      "WAZUH_30118",
			Description: "ModSecurity: Access attempt blocked.",
			Severity:    6,
			condition:   "field:message ~= (?i)mod_security: Access denied\\|ModSecurity: Access denied",
		},
		{
			RuleID:      "WAZUH_30120",
			Description: "Apache: without resources to run.",
			Severity:    12,
			condition:   "field:message ~= (?i)Resource temporarily unavailable:",
		},
		{
			RuleID:      "WAZUH_30201",
			Description: "ModSecurity: Access denied.",
			Severity:    6,
			condition:   "field:message ~= ^mod_security-message: Access denied ",
		},
		{
			RuleID:      "WAZUH_30304",
			Description: "Apache: Segmentation fault.",
			Severity:    12,
			condition:   "field:message ~= (?i)exit signal Segmentation Fault",
		},
		{
			RuleID:      "WAZUH_30318",
			Description: "Apache: PHP Notice in Apache log",
			Severity:    5,
			condition:   "field:message ~= (?i)PHP Notice:",
		},
		{
			RuleID:      "WAZUH_30411",
			Description: "ModSecurity: Rejected a query",
			Severity:    7,
			MITRE:       "T1083",
			condition:   "field:message ~= (?i)with code 403",
		},
		{
			RuleID:      "WAZUH_31202",
			Description: "Zeus warning log.",
			Severity:    4,
			condition:   "field:message ~= ^[\\S+ \\S+] WARN:",
		},
		{
			RuleID:      "WAZUH_31203",
			Description: "Zeus serious log.",
			Severity:    9,
			condition:   "field:message ~= ^[\\S+ \\S+] SERIOUS:",
		},
		{
			RuleID:      "WAZUH_31204",
			Description: "Zeus fatal log.",
			Severity:    12,
			condition:   "field:message ~= ^[\\S+ \\S+] FATAL:",
		},
		{
			RuleID:      "WAZUH_31205",
			Description: "Zeus: Admin authentication failed.",
			Severity:    8,
			condition:   "field:message ~= (?i)admin:Authentication failure",
		},
		{
			RuleID:      "WAZUH_31301",
			Description: "Nginx error message.",
			Severity:    3,
			condition:   "field:message ~= ^\\S+ \\S+ [error] ",
		},
		{
			RuleID:      "WAZUH_31302",
			Description: "Nginx warning message.",
			Severity:    3,
			condition:   "field:message ~= ^\\S+ \\S+ [warn] ",
		},
		{
			RuleID:      "WAZUH_31303",
			Description: "Nginx critical message.",
			Severity:    5,
			condition:   "field:message ~= ^\\S+ \\S+ [crit] ",
		},
		{
			RuleID:      "WAZUH_31315",
			Description: "Nginx: Web authentication failed.",
			Severity:    5,
			condition:   "field:message ~= (?i) password mismatch, client\\| was not found in ",
		},
		{
			RuleID:      "WAZUH_31320",
			Description: "Nginx: Invalid URI, file name too long.",
			Severity:    10,
			condition:   "field:message ~= (?i)failed \\(36: File name too long\\)",
		},
		{
			RuleID:      "WAZUH_31333",
			Description: "ModSecurity rejected a query",
			Severity:    7,
			MITRE:       "T1083",
			condition:   "field:message ~= (?i)with code 403",
		},
		{
			RuleID:      "WAZUH_31334",
			Description: "NAXSI warning",
			Severity:    3,
			condition:   "field:message ~= (?i)NAXSI_FMT:",
		},
		{
			RuleID:      "WAZUH_31335",
			Description: "NAXSI rejected a query",
			Severity:    7,
			MITRE:       "T1083",
			condition:   "field:message ~= (?i)block=1",
		},
		{
			RuleID:      "WAZUH_31411",
			Description: "PHP web attack.",
			Severity:    6,
			MITRE:       "T1190,T1071.001",
			condition:   "field:message ~= (?i) expects parameter 1 to be string, array given in",
		},
		{
			RuleID:      "WAZUH_31412",
			Description: "PHP internal error (missing file).",
			Severity:    5,
			condition:   "field:message ~= (?i)Failed opening\\|failed to open stream",
		},
		{
			RuleID:      "WAZUH_31413",
			Description: "PHP internal error (server out of space).",
			Severity:    5,
			MITRE:       "T1561.001",
			condition:   "field:message ~= (?i)bytes written, possibly out of free disk space in",
		},
		{
			RuleID:      "WAZUH_31421",
			Description: "PHP internal error (missing file or function).",
			Severity:    5,
			condition:   "field:message ~= (?i)Failed opening required \\|Call to undefined function ",
		},
		{
			RuleID:      "WAZUH_31501",
			Description: "WordPress Comment Spam (coming from a fake search engine UA).",
			Severity:    6,
			MITRE:       "T1203",
			condition:   "field:message ~= (?i)POST /",
		},
		{
			RuleID:      "WAZUH_31502",
			Description: "TimThumb vulnerability exploit attempt.",
			Severity:    6,
			MITRE:       "T1212",
			condition:   "field:message ~=  \"GET \\S+thumb.php?src=\\S+.php",
		},
		{
			RuleID:      "WAZUH_31503",
			Description: "osCommerce login.php bypass attempt.",
			Severity:    6,
			MITRE:       "T1190",
			condition:   "field:message ~=  \"POST /\\S+.php/login.php?cPath=",
		},
		{
			RuleID:      "WAZUH_31504",
			Description: "osCommerce file manager login.php bypass attempt.",
			Severity:    6,
			MITRE:       "T1078",
			condition:   "field:message ~= /admin/\\w+.php/login.php",
		},
		{
			RuleID:      "WAZUH_31505",
			Description: "TimThumb backdoor access attempt.",
			Severity:    6,
			MITRE:       "T1505.003",
			condition:   "field:message ~=  \"GET /\\S+/cache/external\\S+.php",
		},
		{
			RuleID:      "WAZUH_31506",
			Description: "Cart.php directory transversal attempt.",
			Severity:    6,
			MITRE:       "T1210,T1190",
			condition:   "field:message ~=  \"GET /\\S+cart.php?\\S+templatefile=../",
		},
		{
			RuleID:      "WAZUH_31508",
			Description: "Blacklisted user agent (known malicious user agent).",
			Severity:    6,
			condition:   "field:message ~= (?i) \"ZmEu\"\\| \"libwww-perl/\\|\"the beast\"\\|\"Morfeus\\|\"ZmEu\\|\"Nikto\\|\"w3af\\.sourceforge\\.net\\| Jorgee\"\\|\"Proxy Gear Pro\\|\"DataCha0s",
		},
		{
			RuleID:      "WAZUH_31509",
			Description: "CMS (WordPress or Joomla) login attempt.",
			Severity:    3,
			MITRE:       "T1110.001",
			condition:   "field:message ~= ] \"POST \\S+wp-login.php| \"POST /administrator",
		},
		{
			RuleID:      "WAZUH_31512",
			Description: "Uploadify vulnerability exploit attempt.",
			Severity:    6,
			MITRE:       "T1210",
			condition:   "field:message ~=  \"GET /\\S+/uploadify.php?src=http://\\S+.php",
		},
		{
			RuleID:      "WAZUH_31513",
			Description: "BBS delete.php exploit attempt.",
			Severity:    6,
			MITRE:       "T1210",
			condition:   "field:message ~=  \"GET \\S+/delete.php?board_skin_path=http://\\S+.php",
		},
		{
			RuleID:      "WAZUH_31514",
			Description: "Simple shell.php command execution.",
			Severity:    6,
			MITRE:       "T1505.003,T1203",
			condition:   "field:message ~=  \"GET \\S+/shell.php?cmd=",
		},
		{
			RuleID:      "WAZUH_31530",
			Description: "POST request received.",
			Severity:    3,
			condition:   "field:message ~= (?i)\\] \"POST ",
		},
		{
			RuleID:      "WAZUH_31550",
			Description: "Anomaly URL query (attempting to pass null termination).",
			Severity:    6,
			MITRE:       "T1555.003",
			condition:   "field:message ~=  \"GET /\\S+.php?\\S+%00",
		},
		{
			RuleID:      "WAZUH_40703",
			Description: "Systemd: Service has entered a failed state, and likely has not started.",
			Severity:    5,
			condition:   "field:message ~= (?i)entered failed state",
		},
		{
			RuleID:      "WAZUH_40704",
			Description: "Systemd: Service exited due to a failure.",
			Severity:    5,
			condition:   "field:message ~= (?i)status=1/FAILURE",
		},
		{
			RuleID:      "WAZUH_40705",
			Description: "Systemd: System time has been changed.",
			Severity:    5,
			condition:   "field:message ~= (?i)Time has been changed\\$",
		},
		{
			RuleID:      "WAZUH_40902",
			Description: "firewalld: Incorrect chain/target/match.",
			Severity:    3,
			condition:   "field:message ~= (?i) No chain/target/match by that name\\.\\$",
		},
		{
			RuleID:      "WAZUH_50105",
			Description: "MySQL: authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= ^MySQL log: \\d+ \\S+ \\d+ Connect",
		},
		{
			RuleID:      "WAZUH_50106",
			Description: "MySQL: authentication failure.",
			Severity:    9,
			condition:   "field:message ~= (?i)Access denied for user",
		},
		{
			RuleID:      "WAZUH_50108",
			Description: "MySQL: User disconnected from database.",
			Severity:    3,
			condition:   "field:message ~= ^MySQL log: \\d+ \\S+ \\d+ Quit",
		},
		{
			RuleID:      "WAZUH_50120",
			Description: "MySQL: shutdown message.",
			Severity:    12,
			MITRE:       "T1529",
			condition:   "field:message ~= (?i)mysqld ended\\|Shutdown complete",
		},
		{
			RuleID:      "WAZUH_50121",
			Description: "MySQL: startup message.",
			Severity:    3,
			condition:   "field:message ~= (?i)mysqld started\\|mysqld restarted",
		},
		{
			RuleID:      "WAZUH_50125",
			Description: "MySQL: error.",
			Severity:    5,
			condition:   "field:message ~= ^MySQL log: \\d+ \\S+ \\d+ [ERROR]",
		},
		{
			RuleID:      "WAZUH_50126",
			Description: "MySQL: fatal error.",
			Severity:    12,
			MITRE:       "T1499",
			condition:   "field:message ~= (?i)Fatal error:",
		},
		{
			RuleID:      "WAZUH_50181",
			Description: "MySQL: error.",
			Severity:    5,
			condition:   "field:message ~= ^MySQL log: \\d+-\\d+-\\d+T\\d+:\\d+:\\d+.\\d+\\.+ \\d+ [ERROR]",
		},
		{
			RuleID:      "WAZUH_50182",
			Description: "MySQL: fatal error.",
			Severity:    12,
			MITRE:       "T1499",
			condition:   "field:message ~= (?i)Fatal error:",
		},
		{
			RuleID:      "WAZUH_50511",
			Description: "PostgreSQL: Database authentication success.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)connection authorized",
		},
		{
			RuleID:      "WAZUH_50512",
			Description: "PostgreSQL: Database authentication failure.",
			Severity:    9,
			condition:   "field:message ~= (?i)authentication failed",
		},
		{
			RuleID:      "WAZUH_50520",
			Description: "PostgreSQL: Database shutdown message.",
			Severity:    12,
			MITRE:       "T1529",
			condition:   "field:message ~= (?i)terminating connection due",
		},
		{
			RuleID:      "WAZUH_50521",
			Description: "PostgreSQL: Database shutdown message.",
			Severity:    12,
			MITRE:       "T1529",
			condition:   "field:message ~= (?i)aborting any active transactions\\|shutting down",
		},
		{
			RuleID:      "WAZUH_51003",
			Description: "Dropbear: Bad password attempt.",
			Severity:    5,
			condition:   "field:message ~= (?i)bad password attempt for",
		},
		{
			RuleID:      "WAZUH_51093",
			Description: "Dropbear: Bad password attempt for non existent user.",
			Severity:    5,
			condition:   "field:message ~= (?i)attempt for nonexistent user",
		},
		{
			RuleID:      "WAZUH_51505",
			Description: "A filesystem was not properly unmounted, likely system crash",
			Severity:    5,
			condition:   "field:message ~= (?i)was not properly unmounted",
		},
		{
			RuleID:      "WAZUH_51510",
			Description: "System shutdown due to temperature",
			Severity:    5,
			condition:   "field:message ~= (?i)Critical temperature, shutting down",
		},
		{
			RuleID:      "WAZUH_51514",
			Description: "Unclean filesystem, run fsck.",
			Severity:    3,
			condition:   "field:message ~= (?i)Filesystem is not clean - run fsck",
		},
		{
			RuleID:      "WAZUH_51518",
			Description: "I/O error on a storage device",
			Severity:    3,
			condition:   "field:message ~= (?i)i/o error on block",
		},
		{
			RuleID:      "WAZUH_51524",
			Description: "System was rebooted.",
			Severity:    4,
			condition:   "field:message ~= (?i)rebooted by",
		},
		{
			RuleID:      "WAZUH_51531",
			Description: "User account deleted.",
			Severity:    3,
			MITRE:       "T1531",
			condition:   "tag:open-userdel",
		},
		{
			RuleID:      "WAZUH_52000",
			Description: "Apparmor messages grouped.",
			Severity:    3,
			condition:   "tag:kernel",
		},
		{
			RuleID:      "WAZUH_52002",
			Description: "Apparmor DENIED",
			Severity:    3,
			condition:   "field:message ~= (?i) apparmor=",
		},
		{
			RuleID:      "WAZUH_52502",
			Description: "ClamAV: Virus detected",
			Severity:    8,
			condition:   "field:message ~= (?i)FOUND",
		},
		{
			RuleID:      "WAZUH_52503",
			Description: "Clamd error",
			Severity:    10,
			condition:   "field:message ~= ^ERROR: ",
		},
		{
			RuleID:      "WAZUH_52504",
			Description: "Clamd warning",
			Severity:    7,
			condition:   "field:message ~= ^WARNING: ",
		},
		{
			RuleID:      "WAZUH_52505",
			Description: "Clamd restarted",
			Severity:    3,
			condition:   "field:message ~= (?i)clamd daemon",
		},
		{
			RuleID:      "WAZUH_52506",
			Description: "Clamd database updated",
			Severity:    3,
			condition:   "field:message ~= (?i)Database modification detected",
		},
		{
			RuleID:      "WAZUH_52507",
			Description: "ClamAV database update",
			Severity:    3,
			condition:   "field:message ~= (?i)ClamAV update process started ",
		},
		{
			RuleID:      "WAZUH_52508",
			Description: "ClamAV database updated",
			Severity:    3,
			condition:   "field:message ~= (?i)Database updated ",
		},
		{
			RuleID:      "WAZUH_52510",
			Description: "Clamd stopped",
			Severity:    6,
			MITRE:       "T1562.001",
			condition:   "field:message ~= (?i)stop\\|Stop",
		},
		{
			RuleID:      "WAZUH_53508",
			Description: "Server TLS certificate verification failed.",
			Severity:    5,
			condition:   "tag:smtpd",
		},
		{
			RuleID:      "WAZUH_80002",
			Description: "Puppet Master started",
			Severity:    5,
			condition:   "field:message ~= ^Starting",
		},
		{
			RuleID:      "WAZUH_80003",
			Description: "Puppet Master stopped",
			Severity:    5,
			condition:   "field:message ~= ^Processing|^Caught",
		},
		{
			RuleID:      "WAZUH_80004",
			Description: "Puppet Master: Permission denied",
			Severity:    5,
			condition:   "field:message ~= ^Permission denied ",
		},
		{
			RuleID:      "WAZUH_80006",
			Description: "Puppet Master: not run - address in use",
			Severity:    7,
			condition:   "field:message ~= ^Could not run: Address already in use",
		},
		{
			RuleID:      "WAZUH_80007",
			Description: "Puppet Master: Manifest Error",
			Severity:    5,
			condition:   "field:message ~= ^Could not|^You cannot|^too few arguments|^Duplicate declaration|^Unrecognised escape sequence|^Invalid parameter|is not|has not been tested|Unknown function|failed|has failure",
		},
		{
			RuleID:      "WAZUH_80008",
			Description: "Puppet Master: Error",
			Severity:    4,
			condition:   "field:message ~= ^Could not|not found|^Not collecting|^The environment must be|^Syntax error|^Failed|failed|has failure",
		},
		{
			RuleID:      "WAZUH_80050",
			Description: "Puppet Agent started",
			Severity:    5,
			condition:   "field:message ~= ^Starting Puppet client",
		},
		{
			RuleID:      "WAZUH_80051",
			Description: "Puppet Agent stopped",
			Severity:    5,
			condition:   "field:message ~= ^Processing|^Caught",
		},
		{
			RuleID:      "WAZUH_80054",
			Description: "Puppet Agent: Error - no file found or does not exist",
			Severity:    4,
			condition:   "field:message ~= ^No \\S+ file found|file \\S+ does not exist",
		},
		{
			RuleID:      "WAZUH_80055",
			Description: "Puppet Agent: Error - feature is missing",
			Severity:    4,
			condition:   "field:message ~= feature \\S+ is missing",
		},
		{
			RuleID:      "WAZUH_80056",
			Description: "Puppet Agent: Error - failed library",
			Severity:    5,
			condition:   "field:message ~= ^Failed to load library",
		},
		{
			RuleID:      "WAZUH_80057",
			Description: "Puppet Agent: Error - failed to apply catalog",
			Severity:    5,
			condition:   "field:message ~= ^Failed to apply catalog",
		},
		{
			RuleID:      "WAZUH_80058",
			Description: "Puppet Agent: connection refused",
			Severity:    10,
			condition:   "field:message ~= (?i)Connection refused - connect",
		},
		{
			RuleID:      "WAZUH_80059",
			Description: "Puppet Agent: Error",
			Severity:    4,
			condition:   "field:message ~= ^Unable to fetch|does not support|Not using cache|Could not retrieve|Failed|failed|has failure",
		},
		{
			RuleID:      "WAZUH_80092",
			Description: "Puppet did not run in the last 30 minutes",
			Severity:    5,
			condition:   "field:message ~= (?i)Puppet: KO",
		},
		{
			RuleID:      "WAZUH_80101",
			Description: "Netscaler: AAA module failed to login the user",
			Severity:    5,
			condition:   "field:message ~= (?i)AAA LOGIN_FAILED",
		},
		{
			RuleID:      "WAZUH_80104",
			Description: "Netscaler: UI/API command executed failed",
			Severity:    4,
			condition:   "field:message ~= (?i)UI CMD_EXECUTED\\|API CMD_EXECUTED",
		},
		{
			RuleID:      "WAZUH_80106",
			Description: "Netscaler: UI/API dangerous command",
			Severity:    10,
			MITRE:       "T1070.004",
			condition:   "field:message ~= (?i)UI CMD_EXECUTED\\|API CMD_EXECUTED",
		},
		{
			RuleID:      "WAZUH_80107",
			Description: "Netscaler: SSLVPN login succeeds",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)SSLVPN LOGIN",
		},
		{
			RuleID:      "WAZUH_80108",
			Description: "Netscaler: SSLVPN session logs out",
			Severity:    3,
			condition:   "field:message ~= (?i)SSLVPN LOGOUT",
		},
		{
			RuleID:      "WAZUH_80111",
			Description: "Netscaler: A non-http resource access is denied by policy engine.",
			Severity:    5,
			condition:   "field:message ~= (?i)SSLVPN NONHTTP_RESOURCEACCESS_DENIED",
		},
		{
			RuleID:      "WAZUH_80113",
			Description: "Netscaler: A http resource access is denied by policy engine",
			Severity:    5,
			MITRE:       "T1133,T1083",
			condition:   "field:message ~= (?i)SSLVPN HTTP_RESOURCEACCESS_DENIED",
		},
		{
			RuleID:      "WAZUH_80115",
			Description: "Netscaler: SSLVPN session: client security check error",
			Severity:    5,
			MITRE:       "T1133",
			condition:   "field:message ~= (?i)SSLVPN CLISEC_CHECK",
		},
		{
			RuleID:      "WAZUH_80116",
			Description: "Netscaler: SSLVPN session: client security expression evaluates to False",
			Severity:    5,
			MITRE:       "T1133",
			condition:   "field:message ~= (?i)SSLVPN CLISEC_EXP_EVAL",
		},
		{
			RuleID:      "WAZUH_80125",
			Description: "Netscaler: Memory internal error",
			Severity:    5,
			condition:   "field:message ~= (?i)EVENT FREEBADMEM\\|EVENT FREEDUPMEM\\|EVENT FREEEXTMEM",
		},
		{
			RuleID:      "WAZUH_80126",
			Description: "Netscaler: HA propagation failed",
			Severity:    5,
			condition:   "field:message ~= (?i)EVENT PROPFAIL",
		},
		{
			RuleID:      "WAZUH_80127",
			Description: "Netscaler: Firewall violation",
			Severity:    3,
			condition:   "field:message ~= (?i)APPFW APPFW_STARTURL\\|APPFW APPFW_DENYURL\\|APPFW APPFW_CONTENT_TYPE\\|APPFW APPFW_REFERER_HEADER\\|APPFW APPFW_CSRF_TAG\\|APPFW APPFW_XSS\\|APPFW APPFW_XML_XSS\\|APPFW APPFW_SQL\\|APPFW APPFW_XML_SQL\\|APPFW APPFW_COOKIE\\|APPFW APPFW_FIELDCONSISTENCY\\|APPFWAPPFW_BUFFEROVERFLOW_URL\\|APPFW APPFW_BUFFEROVER FLOW_COOKIE\\|APPFW APPFW_BUFFEROVERFLOW_HDR\\|APPFW APPFW_FIELDFORMAT\\|APPFW APPFW_SAFECOMMERCE\\|APPFW APPFW_SAFECOMMERCE_XFORM\\|APPFW APPFW_SAFEOBJECT\\|APPFW APPFW_SIGNATURE_MATCH\\|APPFW_RESP APPFW_XML_XSS\\|APPFW_RESP APPFW_XML_SQL",
		},
		{
			RuleID:      "WAZUH_80128",
			Description: "Netscaler: Firewall: Appsecure uthread at 0x%x had a stack error",
			Severity:    5,
			condition:   "field:message ~= (?i)APPFW AF_UTHREAD_STACK_ERR",
		},
		{
			RuleID:      "WAZUH_80129",
			Description: "Netscaler: Firewall: DOS\\DDOS error",
			Severity:    4,
			condition:   "field:message ~= (?i)APPFW APPFW_XML_ERR_DOS\\|APPFW APPFW_XML_DDOS_ERR\\|APPFW_RESP APPFW_XML_DDOS_ERR_MSG_SEND_FAI\\|APPFW_RESP APPFW_XML_DOS_ERR_CHAR_DATA_LENGTH",
		},
		{
			RuleID:      "WAZUH_80134",
			Description: "Netscaler: Login to AAA TM vserver succeeds",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)AAATM LOGIN",
		},
		{
			RuleID:      "WAZUH_80135",
			Description: "Netscaler: AAA TM session logged out",
			Severity:    3,
			condition:   "field:message ~= (?i)AAATM LOGOUT",
		},
		{
			RuleID:      "WAZUH_80136",
			Description: "Netscaler: A AAATM http resource access is denied by policy engine",
			Severity:    5,
			condition:   "field:message ~= (?i)AAATM HTTP_RESOURCEACCESS_DENIED",
		},
		{
			RuleID:      "WAZUH_80138",
			Description: "Netscaler: UI/API login succeeds",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)UI CMD_EXECUTED\\|API CMD_EXECUTED",
		},
		{
			RuleID:      "WAZUH_80139",
			Description: "Netscaler: UI/API login failed",
			Severity:    6,
			condition:   "field:message ~= (?i)UI CMD_EXECUTED\\|API CMD_EXECUTED",
		},
		{
			RuleID:      "WAZUH_80503",
			Description: "Serv-U: User logged in",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)logged in",
		},
		{
			RuleID:      "WAZUH_80504",
			Description: "Serv-U: User logged out",
			Severity:    3,
			condition:   "field:message ~= (?i)logged out",
		},
		{
			RuleID:      "WAZUH_80505",
			Description: "Serv-U: Invalid credentials",
			Severity:    5,
			condition:   "field:message ~= (?i)Invalid login credentials\\|Password wrong too many times",
		},
		{
			RuleID:      "WAZUH_80509",
			Description: "Serv-U: Remote host connected",
			Severity:    3,
			condition:   "field:message ~= (?i)Connected to",
		},
		{
			RuleID:      "WAZUH_80513",
			Description: "Serv-U: File deleted",
			Severity:    3,
			MITRE:       "T1070.004",
			condition:   "field:message ~= (?i)File deleted",
		},
		{
			RuleID:      "WAZUH_80516",
			Description: "Serv-U: Directory deleted",
			Severity:    3,
			MITRE:       "T1070.004",
			condition:   "field:message ~= (?i)Directory deleted",
		},
		{
			RuleID:      "WAZUH_80517",
			Description: "Serv-U: File with extension \".exe\" uploaded",
			Severity:    4,
			condition:   "field:message ~= (?i)Received file",
		},
		{
			RuleID:      "WAZUH_80522",
			Description: "Serv-U: FTP/FTPS Permission denied",
			Severity:    4,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)Permission denied",
		},
		{
			RuleID:      "WAZUH_80523",
			Description: "Serv-U: SFTP (SSH) Permission denied",
			Severity:    4,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)Permission denied",
		},
		{
			RuleID:      "WAZUH_80524",
			Description: "Serv-U: HTTP/HTTPS Permission denied",
			Severity:    4,
			MITRE:       "T1110",
			condition:   "field:message ~= (?i)SESS_PERMISSION_DENIED",
		},
		{
			RuleID:      "WAZUH_80710",
			Description: "Auditd: Device enables promiscuous mode.",
			Severity:    10,
			condition:   "field:message ~= (?i)prom=256",
		},
		{
			RuleID:      "WAZUH_80790",
			Description: "Audit: Created: $(audit.file.name).",
			Severity:    3,
			condition:   "field:message ~= (?i)type=CREATE",
		},
		{
			RuleID:      "WAZUH_80791",
			Description: "Audit: Deleted: $(audit.file.name).",
			Severity:    3,
			MITRE:       "T1070.004",
			condition:   "field:message ~= (?i)type=DELETE",
		},
		{
			RuleID:      "WAZUH_81101",
			Description: "Attached USB Storage",
			Severity:    3,
			condition:   "field:message ~= (?i)New USB device found",
		},
		{
			RuleID:      "WAZUH_81102",
			Description: "USB device disconnected",
			Severity:    3,
			condition:   "field:message ~= (?i)USB disconnect",
		},
		{
			RuleID:      "WAZUH_81303",
			Description: "Redis: Warning / Error",
			Severity:    3,
			condition:   "field:message ~= (?i)WARNING\\|can't\\|not permitted\\|error\\|Error\\|ERROR\\|Failed",
		},
		{
			RuleID:      "WAZUH_81304",
			Description: "Redis: Client connected",
			Severity:    3,
			condition:   "field:message ~= (?i)Accepted ",
		},
		{
			RuleID:      "WAZUH_81305",
			Description: "Redis: Client closed connection",
			Severity:    3,
			condition:   "field:message ~= (?i)Client closed connection",
		},
		{
			RuleID:      "WAZUH_81501",
			Description: "OpenSCAP: Error messages grouped.",
			Severity:    7,
			condition:   "field:message ~= (?i)oscap: ERROR: ",
		},
		{
			RuleID:      "WAZUH_81502",
			Description: "OpenSCAP ERROR: OpenSCAP not installed.",
			Severity:    7,
			condition:   "field:message ~= (?i)OpenSCAP not installed",
		},
		{
			RuleID:      "WAZUH_81503",
			Description: "OpenSCAP ERROR: Impossible to execute OpenSCAP.",
			Severity:    7,
			condition:   "field:message ~= (?i)Impossible to execute OpenSCAP",
		},
		{
			RuleID:      "WAZUH_81504",
			Description: "OpenSCAP ERROR: Wrong configuration - Inexistent policy.",
			Severity:    7,
			condition:   "field:message ~= (?i): File \"",
		},
		{
			RuleID:      "WAZUH_81505",
			Description: "OpenSCAP ERROR: Wrong configuration - Invalid policy.",
			Severity:    7,
			condition:   "field:message ~= (?i)Parsing file ",
		},
		{
			RuleID:      "WAZUH_81506",
			Description: "OpenSCAP ERROR: Problem executing oscap.",
			Severity:    7,
			condition:   "field:message ~= (?i)Executing profile",
		},
		{
			RuleID:      "WAZUH_81507",
			Description: "OpenSCAP ERROR: Wrong configuration - Inexistent profile.",
			Severity:    7,
			condition:   "field:message ~= (?i)Profile",
		},
		{
			RuleID:      "WAZUH_81508",
			Description: "OpenSCAP ERROR: Timeout expired",
			Severity:    7,
			condition:   "field:message ~= (?i)Timeout expired",
		},
		{
			RuleID:      "WAZUH_81509",
			Description: "OpenSCAP ERROR: xsltproc not installed.",
			Severity:    7,
			condition:   "field:message ~= (?i)xsltproc not installed",
		},
		{
			RuleID:      "WAZUH_81540",
			Description: "OpenSCAP Report overview.",
			Severity:    3,
			condition:   "field:message ~= (?i)msg: \"xccdf-overview\"",
		},
		{
			RuleID:      "WAZUH_81560",
			Description: "OpenSCAP Report overview.",
			Severity:    3,
			condition:   "field:message ~= (?i)msg: \"oval-overview\"",
		},
		{
			RuleID:      "WAZUH_81608",
			Description: "Fortigate: Configuration changed.",
			Severity:    7,
			condition:   "field:message ~= (?i)Configuration is changed in the admin session",
		},
		{
			RuleID:      "WAZUH_81610",
			Description: "Fortigate: Default tunneling setting. Could be IPS.",
			Severity:    4,
			condition:   "field:message ~= (?i)http_decoder: HTTP\\.Unknown\\.Tunnelling",
		},
		{
			RuleID:      "WAZUH_81614",
			Description: "Fortigate: SSL VPN user failed login attempt.",
			Severity:    4,
			condition:   "field:message ~= (?i)ssl-login-fail",
		},
		{
			RuleID:      "WAZUH_81620",
			Description: "Fortigate: URL Blocked by Firewall.",
			Severity:    3,
			condition:   "field:message ~= (?i)level=warning\\|level=\"warning\"",
		},
		{
			RuleID:      "WAZUH_81622",
			Description: "Fortigate: VPN user connected.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)level=information\\|level=\"information\"",
		},
		{
			RuleID:      "WAZUH_81624",
			Description: "Fortigate: VPN user disconnected.",
			Severity:    3,
			condition:   "field:message ~= (?i)level=information\\|level=\"information\"",
		},
		{
			RuleID:      "WAZUH_81626",
			Description: "Fortigate: User successfully logged into firewall interface.",
			Severity:    3,
			condition:   "field:message ~= (?i)ui",
		},
		{
			RuleID:      "WAZUH_81628",
			Description: "Fortigate attack detected.",
			Severity:    11,
			condition:   "field:message ~= (?i)attack",
		},
		{
			RuleID:      "WAZUH_81629",
			Description: "Fortigate attack dropped.",
			Severity:    6,
			condition:   "field:message ~= (?i)attack",
		},
		{
			RuleID:      "WAZUH_81630",
			Description: "Fortigate Attack: Session cleared.",
			Severity:    3,
			condition:   "field:message ~= (?i)attack",
		},
		{
			RuleID:      "WAZUH_81633",
			Description: "Fortigate: App passed by firewall.",
			Severity:    3,
			condition:   "field:message ~= (?i)subtype=\"app-ctrl\"\\|subtype=app-ctrl",
		},
		{
			RuleID:      "WAZUH_81634",
			Description: "Fortigate: App blocked by firewall.",
			Severity:    5,
			condition:   "field:message ~= (?i)subtype=\"app-ctrl\"\\|subtype=app-ctrl",
		},
		{
			RuleID:      "WAZUH_81638",
			Description: "Fortigate: Virus detected.",
			Severity:    6,
			condition:   "field:message ~= (?i)subtype=virus\\|subtype=\"virus\"",
		},
		{
			RuleID:      "WAZUH_81642",
			Description: "Fortigate: Virtual cluster detected member join.",
			Severity:    3,
			condition:   "field:message ~= (?i)subtype=\"ha\" level=\"critical\"\\|subtype=ha level=critical",
		},
		{
			RuleID:      "WAZUH_81643",
			Description: "Fortigate: SSL fatal alert.",
			Severity:    7,
			condition:   "field:message ~= (?i)subtype=\"wad\" level=\"error\"\\|subtype=wad level=error",
		},
		{
			RuleID:      "WAZUH_81644",
			Description: "Fortigate: Blocked URL belongs to a denied category in policy.",
			Severity:    6,
			condition:   "field:message ~= (?i)type=\"utm\" subtype=\"webfilter\"\\|type=utm subtype=webfilter",
		},
		{
			RuleID:      "WAZUH_81645",
			Description: "Fortigate: SSL anomalies. Blocked connection.",
			Severity:    5,
			condition:   "field:message ~= (?i)type=\"utm\" subtype=\"ssl\" eventtype=\"ssl-anomalies\"\\|type=utm subtype=ssl eventtype=ssl-anomalies",
		},
		{
			RuleID:      "WAZUH_81646",
			Description: "Fortigate: File was blocked by file filter.",
			Severity:    5,
			condition:   "field:message ~= (?i)type=\"utm\" subtype=\"cifs\" eventtype=\"cifs-filefilter\"\\|type=utm subtype=cifs eventtype=cifs-filefilter",
		},
		{
			RuleID:      "WAZUH_81709",
			Description: "HP 5500 EI - Warning event: Authentication failure",
			Severity:    4,
			condition:   "field:message ~= (?i)failed to log in\\|failed to login\\|authentication failed\\|Authentication is failed",
		},
		{
			RuleID:      "WAZUH_81801",
			Description: "OpenVPN: User logged in",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Peer Connection Initiated with",
		},
		{
			RuleID:      "WAZUH_81803",
			Description: "OpenVPN: Connection Certificate Failed",
			Severity:    4,
			MITRE:       "T1133",
			condition:   "field:message ~= (?i)TLS Error\\|TLS Auth Error",
		},
		{
			RuleID:      "WAZUH_81805",
			Description: "OpenVPN LDAP Bind Failure: $(ldap_data.error_message)",
			Severity:    5,
			condition:   "field:message ~= ^LDAP bind failed:",
		},
		{
			RuleID:      "WAZUH_81806",
			Description: "OpenVPN LDAP Logon Failure: $(ldap_data.Username) [$(ldap_data.Department)]",
			Severity:    5,
			condition:   "field:message ~= ^Incorrect password supplied for LDAP DN",
		},
		{
			RuleID:      "WAZUH_82101",
			Description: "Sophos Cloud Scheduled Scan started",
			Severity:    3,
			condition:   "field:message ~= (?i)Scan 'Sophos Cloud Scheduled Scan' started",
		},
		{
			RuleID:      "WAZUH_82102",
			Description: "Sophos Cloud Scheduled Scan completed",
			Severity:    3,
			condition:   "field:message ~= (?i)Scan 'Sophos Cloud Scheduled Scan' completed",
		},
		{
			RuleID:      "WAZUH_82103",
			Description: "User has started on-access scanning for this machine.",
			Severity:    3,
			condition:   "field:message ~= (?i)has started",
		},
		{
			RuleID:      "WAZUH_82104",
			Description: "User has stopped on-access scanning for this machine.",
			Severity:    3,
			condition:   "field:message ~= (?i)has stopped",
		},
		{
			RuleID:      "WAZUH_82105",
			Description: "Sophos database updated",
			Severity:    3,
			condition:   "field:message ~= (?i)detection data version",
		},
		{
			RuleID:      "WAZUH_82203",
			Description: "FreeIPA: Authentication fail",
			Severity:    4,
			condition:   "field:message ~= (?i)Password incorrect",
		},
		{
			RuleID:      "WAZUH_82401",
			Description: "Cisco eStreamer: SERVER-MYSQL failed login attempt",
			Severity:    5,
			condition:   "field:message ~= (?i)failed Oracle Mysql login attempt",
		},
		{
			RuleID:      "WAZUH_82402",
			Description: "Cisco eStreamer: SERVER-MYSQL login attempt from unauthorized location",
			Severity:    5,
			condition:   "field:message ~= (?i)login attempt from unauthorized location",
		},
		{
			RuleID:      "WAZUH_82403",
			Description: "Cisco eStreamer: SERVER-MYSQL client authentication bypass attempt",
			Severity:    5,
			condition:   "field:message ~= (?i)client authentication bypass attempt",
		},
		{
			RuleID:      "WAZUH_82404",
			Description: "Cisco eStreamer: SERVER-MYSQL show databases attempt",
			Severity:    5,
			condition:   "field:message ~= (?i)show databases attempt",
		},
		{
			RuleID:      "WAZUH_82405",
			Description: "Cisco eStreamer: APP-DETECT DNS request for potential malware",
			Severity:    9,
			MITRE:       "T1071.004",
			condition:   "field:message ~= (?i)DNS request for potential malware",
		},
		{
			RuleID:      "WAZUH_85001",
			Description: "Starting up database.",
			Severity:    3,
			condition:   "field:message ~= (?i)Starting up database",
		},
		{
			RuleID:      "WAZUH_85002",
			Description: "Attempting to load library.",
			Severity:    3,
			condition:   "field:message ~= (?i)Attempting to load library",
		},
		{
			RuleID:      "WAZUH_85003",
			Description: "SQL Server process ID.",
			Severity:    3,
			condition:   "field:message ~= (?i)Server process ID is",
		},
		{
			RuleID:      "WAZUH_85004",
			Description: "SQL Server login success.",
			Severity:    5,
			condition:   "field:message ~= (?i)Login succeeded for user",
		},
		{
			RuleID:      "WAZUH_85005",
			Description: "SQL Server login failed.",
			Severity:    7,
			condition:   "field:message ~= (?i)Login failed for user",
		},
		{
			RuleID:      "WAZUH_85007",
			Description: "SQL Server library use.",
			Severity:    3,
			condition:   "field:message ~= (?i)Using ",
		},
		{
			RuleID:      "WAZUH_85008",
			Description: "SQL Server Network Interface library unregistered",
			Severity:    6,
			condition:   "field:message ~= (?i)The SQL Server Network Interface library could not register the Service Principal Name",
		},
		{
			RuleID:      "WAZUH_85009",
			Description: "SQL Server error.",
			Severity:    3,
			condition:   "field:message ~= (?i)Error: ",
		},
		{
			RuleID:      "WAZUH_85010",
			Description: "SQL Server filestream information.",
			Severity:    3,
			condition:   "field:message ~= (?i)FILESTREAM: ",
		},
		{
			RuleID:      "WAZUH_85501",
			Description: "Identity Guard: User authentication failed.",
			Severity:    7,
			condition:   "field:message ~= (?i)failed authentication",
		},
		{
			RuleID:      "WAZUH_85756",
			Description: "MongoDB: Connection accepted",
			Severity:    3,
			condition:   "field:message ~= (?i)connection accepted",
		},
		{
			RuleID:      "WAZUH_85757",
			Description: "MongoDB: End connection",
			Severity:    3,
			condition:   "field:message ~= (?i)end connection",
		},
		{
			RuleID:      "WAZUH_85758",
			Description: "MongoDB: Successfully authentication",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Successfully authenticated",
		},
		{
			RuleID:      "WAZUH_85759",
			Description: "MongoDB: Failed authentication",
			Severity:    4,
			condition:   "field:message ~= (?i)authentication failed for",
		},
		{
			RuleID:      "WAZUH_85761",
			Description: "MongoDB: Execute commands without the necessary privileges",
			Severity:    7,
			condition:   "field:message ~= Unauthorized not authorized on \\S+ to execute command",
		},
		{
			RuleID:      "WAZUH_86005",
			Description: "Docker: Error - unauthorized action",
			Severity:    4,
			condition:   "field:message ~= (?i)unauthorized",
		},
		{
			RuleID:      "WAZUH_86006",
			Description: "Docker: Error - denied action",
			Severity:    4,
			condition:   "field:message ~= (?i)denied: User",
		},
		{
			RuleID:      "WAZUH_86254",
			Description: "Jenkins: Installation successful",
			Severity:    3,
			condition:   "field:message ~= (?i)Installation successful:",
		},
		{
			RuleID:      "WAZUH_86255",
			Description: "Jenkins: Started SSHD",
			Severity:    3,
			condition:   "field:message ~= (?i)Started SSHD",
		},
		{
			RuleID:      "WAZUH_86801",
			Description: "VShell connection attempt successful",
			Severity:    3,
			condition:   "field:message ~= (?i)Connection accepted from",
		},
		{
			RuleID:      "WAZUH_86802",
			Description: "VShell user failed to login or user does not exist",
			Severity:    5,
			condition:   "field:message ~= Login failed|Authentication for (\\w+) failed",
		},
		{
			RuleID:      "WAZUH_86803",
			Description: "VShell user used the maximum number of password attempts.",
			Severity:    7,
			MITRE:       "T1110",
			condition:   "field:message ~= Maximum authentication retries for user (\\w+) exceeded",
		},
		{
			RuleID:      "WAZUH_86804",
			Description: "Host is trying to connect to VShell server but exists in the deny file.",
			Severity:    10,
			condition:   "field:message ~= Connection from (\\d+.\\d+.\\d+.\\d+) rejected by Deny Hosts file",
		},
		{
			RuleID:      "WAZUH_86805",
			Description: "VShell user successfully authenticated.",
			Severity:    3,
			condition:   "field:message ~= password for user (\\S+) accepted",
		},
		{
			RuleID:      "WAZUH_87201",
			Description: "Proxmox VE authentication failed.",
			Severity:    6,
			condition:   "field:message ~= (?i)authentication failure; ",
		},
		{
			RuleID:      "WAZUH_87203",
			Description: "Proxmox VE authentication succeeded.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i) successful auth for user ",
		},
		{
			RuleID:      "WAZUH_87301",
			Description: "ownCloud authentication failed.",
			Severity:    6,
			condition:   "field:message ~= (?i)Login failed: ",
		},
		{
			RuleID:      "WAZUH_87303",
			Description: "ownCloud possible malicious request.",
			Severity:    6,
			MITRE:       "T1203,T1102",
			condition:   "field:message ~= (?i)Passed filename is not valid, might be malicious ",
		},
		{
			RuleID:      "WAZUH_22402",
			Description: "$(vuls.scanned_cve) has a update date lower than $(vuls.days) days.",
			Severity:    7,
			condition:   "field:message ~= (?i)has a update date lower",
		},
		{
			RuleID:      "WAZUH_87502",
			Description: "Exim: Auth failed.",
			Severity:    5,
			condition:   "field:message ~= (?i)authenticator failed",
		},
		{
			RuleID:      "WAZUH_87506",
			Description: "Exim: syntax or protocol errors.",
			Severity:    5,
			condition:   "field:message ~= (?i)dropped: too many syntax or protocol errors",
		},
		{
			RuleID:      "WAZUH_87507",
			Description: "Exim: SMTP protocol synchronization error (input sent without waiting for greeting).",
			Severity:    6,
			condition:   "field:message ~= (?i)input sent without waiting for greeting",
		},
		{
			RuleID:      "WAZUH_87508",
			Description: "Exim: RCPT rejected. Error: $(error_message).",
			Severity:    6,
			condition:   "tag:windows-date-format",
		},
		{
			RuleID:      "WAZUH_87601",
			Description: "OpenVAS (gsad) authentication failed.",
			Severity:    6,
			condition:   "field:message ~= (?i)Authentication failure for ",
		},
		{
			RuleID:      "WAZUH_87603",
			Description: "OpenVAS (gsad) authentication succeeded.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "field:message ~= (?i)Authentication success for ",
		},
		{
			RuleID:      "WAZUH_24001",
			Description: "osquery error message",
			Severity:    5,
			condition:   "field:message ~= ^E\\d\\d\\d\\d ",
		},
		{
			RuleID:      "WAZUH_24002",
			Description: "osquery warning message",
			Severity:    3,
			condition:   "field:message ~= ^W\\d\\d\\d\\d ",
		},
		{
			RuleID:      "WAZUH_90499",
			Description: "Vipre informational message",
			Severity:    3,
			condition:   "field:message ~= (?i)SBAMSvc",
		},
		{
			RuleID:      "WAZUH_64001",
			Description: "ASA alert message.",
			Severity:    6,
			condition:   "field:message ~= (?i)%ASA-1-",
		},
		{
			RuleID:      "WAZUH_64002",
			Description: "ASA critical message.",
			Severity:    5,
			condition:   "field:message ~= (?i)%ASA-2-",
		},
		{
			RuleID:      "WAZUH_64003",
			Description: "ASA error message.",
			Severity:    4,
			condition:   "field:message ~= (?i)%ASA-3-",
		},
		{
			RuleID:      "WAZUH_64004",
			Description: "ASA warning message.",
			Severity:    3,
			condition:   "field:message ~= (?i)%ASA-4-",
		},
		{
			RuleID:      "WAZUH_64022",
			Description: "ASA: Firewall failover pair communication problem.",
			Severity:    8,
			condition:   "field:message ~= (?i)Failed\\|Lost Failover",
		},
		{
			RuleID:      "WAZUH_88212",
			Description: "NextCloud authentication failed.",
			Severity:    6,
			condition:   "field:message ~= (?i)Login failed: ",
		},
		{
			RuleID:      "WAZUH_88204",
			Description: "NextCloud possible malicious request.",
			Severity:    3,
			condition:   "field:message ~= (?i)Passed filename is not valid, might be malicious ",
		},
		{
			RuleID:      "WAZUH_88210",
			Description: "NextCloud logout successful.",
			Severity:    3,
			condition:   "field:message ~= (?i)Logout occurred",
		},
		{
			RuleID:      "WAZUH_88211",
			Description: "NextCloud authentication successful.",
			Severity:    3,
			condition:   "field:message ~= (?i)Login successful: ",
		},
		{
			RuleID:      "WAZUH_88213",
			Description: "NextCloud file accessed.",
			Severity:    3,
			condition:   "field:message ~= (?i)File accessed: ",
		},
		{
			RuleID:      "WAZUH_88214",
			Description: "NextCloud file created.",
			Severity:    3,
			condition:   "field:message ~= (?i)File created: ",
		},
		{
			RuleID:      "WAZUH_88215",
			Description: "NextCloud file deleted.",
			Severity:    3,
			condition:   "field:message ~= (?i)File deleted: ",
		},
		{
			RuleID:      "WAZUH_88216",
			Description: "NextCloud preview accessed.",
			Severity:    3,
			condition:   "field:message ~= (?i)Preview accessed: ",
		},
		{
			RuleID:      "WAZUH_64201",
			Description: "Panda: Alert message received.",
			Severity:    7,
			condition:   "field:message ~= (?i)Alert",
		},
		{
			RuleID:      "WAZUH_64231",
			Description: "VPN routing: The connection was routed through the gateway acting as a central hub.",
			Severity:    3,
			condition:   "field:message ~= (?i)VPN routing",
		},
		{
			RuleID:      "WAZUH_64238",
			Description: "Replace Malicious code: Malicious code in the connection was replaced.",
			Severity:    7,
			MITRE:       "T1001",
			condition:   "field:message ~= (?i)Replace Malicious code",
		},
		{
			RuleID:      "WAZUH_92601",
			Description: "Executed python script from /tmp/ folder.",
			Severity:    6,
			MITRE:       "T1059.006",
			condition:   "field:message ~= (?i)a\\d=\"\\w\\+\\\\.py\"\\.\\+cwd=\"/tmp\"\\|a\\d=\"/tmp/\\.\\+\\\\.py",
		},
		{
			RuleID:      "WAZUH_92602",
			Description: "Suspicious python script matches Impacket signature, possible use of stolen credentials or pass the hash attack.",
			Severity:    12,
			MITRE:       "T1059.006,T1550.002",
			condition:   "field:message ~= (?i)\\(psexec\\.py\\|smbexec\\.py\\)\\.\\+a\\d=\"-hashes\"\\.\\+a\\d=\"\\.\\+:\\.\\+",
		},
		{
			RuleID:      "WAZUH_91520",
			Description: "FTD: Firewall failover pair communication problem.",
			Severity:    8,
			condition:   "field:message ~= (?i)Failed\\|Lost Failover",
		},
		{
			RuleID:      "WAZUH_89600",
			Description: "$(application) has been granted permission to $(service) at $(time).",
			Severity:    5,
			MITRE:       "T1222.002",
			condition:   "tag:macOS_tccd",
		},
		{
			RuleID:      "WAZUH_89601",
			Description: "$(application) has been denied permission to $(service) at $(time).",
			Severity:    5,
			MITRE:       "T1222.002",
			condition:   "tag:macOS_tccd",
		},
		{
			RuleID:      "WAZUH_89602",
			Description: "Screen unlocked with userID:$(userID).",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "tag:macOS_loginwindow",
		},
		{
			RuleID:      "WAZUH_89603",
			Description: "Screen locked with userID:$(userID).",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "tag:macOS_loginwindow",
		},
		{
			RuleID:      "WAZUH_89604",
			Description: "User logoff.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "tag:macOS_sessionlogoutd",
		},
		{
			RuleID:      "WAZUH_89605",
			Description: "User login.",
			Severity:    3,
			MITRE:       "T1078",
			condition:   "tag:macOS_loginwindow",
		},
		{
			RuleID:      "WAZUH_89606",
			Description: "Attempt to connect to screen sharing with username $(dstuser) from $(ip_address) failed.",
			Severity:    5,
			MITRE:       "T1021,T1078",
			condition:   "tag:macOS_screensharingd",
		},
		{
			RuleID:      "WAZUH_89607",
			Description: "Attempt to connect to screen sharing with username $(dstuser) from $(ip_address) succeeded.",
			Severity:    3,
			MITRE:       "T1021,T1078",
			condition:   "tag:macOS_screensharingd",
		},
		{
			RuleID:      "WAZUH_89608",
			Description: "Session $(sessionId) has been created.",
			Severity:    3,
			condition:   "tag:macOS_securityd",
		},
		{
			RuleID:      "WAZUH_89609",
			Description: "Session $(sessionId) has been destroyed.",
			Severity:    3,
			condition:   "tag:macOS_securityd",
		},
		{
			RuleID:      "WAZUH_99029",
			Description: "Possible IAM Role backdooring: IAM role granted from an external account.",
			Severity:    12,
			MITRE:       "T1098.001",
			condition:   "field:message ~= (?i)sts:AssumeRole",
		},
	}
}
