package main

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type WazuhDecoderDef struct {
	Name        string `xml:"name,attr"`
	Parent      string `xml:"parent"`
	ProgramName string `xml:"program_name"`
	PreMatch    string `xml:"prematch"`
	Regex       string `xml:"regex"`
	Order       string `xml:"order"`
}

type WazuhDecoderGroup struct {
	XMLName  xml.Name          `xml:"decoder"`
	Decoders []WazuhDecoderDef `xml:"decoder"`
	Name     string            `xml:"name,attr"`
	Parent   string            `xml:"parent,attr"`
	Program  string            `xml:"program_name"`
	PreMatch string            `xml:"prematch"`
	Regex    string            `xml:"regex"`
	Order    string            `xml:"order"`
}

type DecoderEntry struct {
	Name        string   `json:"name"`
	Parent      string   `json:"parent,omitempty"`
	ProgramName string   `json:"program_name,omitempty"`
	PreMatch    string   `json:"prematch,omitempty"`
	Regex       string   `json:"regex,omitempty"`
	Order       []string `json:"order,omitempty"`
}

func convertDecoders() {
	decodersDir := `C:\Users\YMA\AppData\Local\Temp\wazuh-rules\ruleset\decoders`
	outputPath := `D:\Projects_And_Learning\AI\Trace\dev\internal\siem\wazuh_decoders_gen.go`

	var allDecoders []DecoderEntry

	files, _ := os.ReadDir(decodersDir)
	for _, f := range files {
		if filepath.Ext(f.Name()) != ".xml" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(decodersDir, f.Name()))
		if err != nil {
			continue
		}

		content := string(data)
		decoderTags := extractDecoderTags(content)

		for _, xmlStr := range decoderTags {
			var d WazuhDecoderDef
			if err := xml.Unmarshal([]byte(xmlStr), &d); err != nil {
				continue
			}
			if d.Name == "" {
				continue
			}
			if d.Regex == "" && d.PreMatch == "" && d.ProgramName == "" {
				continue
			}
			entry := DecoderEntry{
				Name:        d.Name,
				Parent:      d.Parent,
				ProgramName: d.ProgramName,
				PreMatch:    d.PreMatch,
				Regex:       d.Regex,
			}
			if d.Order != "" {
				entry.Order = strings.Split(d.Order, "|")
			}
			allDecoders = append(allDecoders, entry)
		}
	}

	fmt.Printf("Converted %d decoders from %d files\n", len(allDecoders), len(files))

	jsonData, _ := json.Marshal(allDecoders)
	var goBuf strings.Builder
	goBuf.WriteString("package siem\n\n")
	goBuf.WriteString("// Code generated by tools/wazuh-converter. DO NOT EDIT.\n")
	goBuf.WriteString("var wazuhDecodersJSON = `")
	goBuf.WriteString(string(jsonData))
	goBuf.WriteString("`\n")

	os.WriteFile(outputPath, []byte(goBuf.String()), 0644)
	fmt.Printf("Written to %s\n", outputPath)
}

func extractDecoderTags(content string) []string {
	var tags []string
	start := 0
	for {
		openIdx := strings.Index(content[start:], "<decoder ")
		if openIdx < 0 {
			openIdx = strings.Index(content[start:], "<decoder>")
		}
		if openIdx < 0 {
			break
		}
		openIdx += start

		closeIdx := strings.Index(content[openIdx:], "</decoder>")
		if closeIdx < 0 {
			break
		}
		closeIdx += openIdx + len("</decoder>")

		tags = append(tags, content[openIdx:closeIdx])
		start = closeIdx
	}
	return tags
}

func convertLists() {
	listsDir := `C:\Users\YMA\AppData\Local\Temp\wazuh-rules\ruleset\lists`
	outputPath := `D:\Projects_And_Learning\AI\Trace\dev\internal\siem\wazuh_lists_gen.go`

	data := make(map[string]map[string]string)

	filepath.Walk(listsDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(listsDir, path)
		name := strings.ReplaceAll(rel, "\\", "_")
		name = strings.ReplaceAll(name, "/", "_")
		name = strings.TrimSuffix(name, filepath.Ext(name))

		entries := make(map[string]string)
		content, _ := os.ReadFile(path)
		for _, line := range strings.Split(string(content), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "TEMPLATE:") || strings.HasPrefix(line, "#") {
				continue
			}
			if strings.Contains(line, ":") {
				parts := strings.SplitN(line, ":", 2)
				entries[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			} else {
				entries[line] = ""
			}
		}
		if len(entries) > 0 {
			data[name] = entries
		}
		return nil
	})

	jsonData, _ := json.Marshal(data)
	var buf strings.Builder
	buf.WriteString("package siem\n\n")
	buf.WriteString("// Code generated by tools/wazuh-converter. DO NOT EDIT.\n")
	buf.WriteString("var wazuhListsJSON = `")
	buf.WriteString(string(jsonData))
	buf.WriteString("`\n")

	os.WriteFile(outputPath, []byte(buf.String()), 0644)
	fmt.Printf("Converted %d lists to %s\n", len(data), outputPath)
}

func convertMitre() {
	inputPath := `C:\Users\YMA\AppData\Local\Temp\wazuh-rules\ruleset\mitre\enterprise-attack.json`
	outputPath := `D:\Projects_And_Learning\AI\Trace\dev\internal\archive\mitre_seed_gen.go`

	data, err := os.ReadFile(inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read mitre: %v\n", err)
		return
	}

	var bundle struct {
		Objects []struct {
			ID        string `json:"id"`
			Type      string `json:"type"`
			Name      string `json:"name"`
			Created   string `json:"created"`
			Modified  string `json:"modified"`
			Description string `json:"description"`
			KillChainPhases []struct {
				PhaseName string `json:"phase_name"`
			} `json:"kill_chain_phases"`
			ExternalRefs []struct {
				Source   string `json:"source_name"`
				ExternalID string `json:"external_id"`
			} `json:"external_references"`
			Platforms []string `json:"x_mitre_platforms"`
			Detection    string `json:"x_mitre_detection"`
		} `json:"objects"`
	}

	if err := json.Unmarshal(data, &bundle); err != nil {
		fmt.Fprintf(os.Stderr, "parse mitre: %v\n", err)
		return
	}

	tacticShort := make(map[string]string)
	mitreID := make(map[string]string)
	mitigations := make(map[string]string)

	for _, obj := range bundle.Objects {
		if obj.Type == "x-mitre-tactic" {
			for _, r := range obj.ExternalRefs {
				if r.Source == "mitre-attack" && r.ExternalID != "" {
					tacticShort[r.ExternalID] = obj.Name
				}
			}
		}
	}

	for _, obj := range bundle.Objects {
		if obj.Type == "course-of-action" {
			for _, r := range obj.ExternalRefs {
				if r.Source == "mitre-attack" && r.ExternalID != "" {
					mitreID[r.ExternalID] = obj.ID
					mitigations[r.ExternalID] = obj.Name
				}
			}
		}
	}

	type Technique struct {
		ID          string   `json:"id"`
		Name        string   `json:"name"`
		Description string   `json:"description"`
		Tactics     []string `json:"tactics"`
		Platforms   []string `json:"platforms"`
		Mitigations []string `json:"mitigations"`
		Detection   []string `json:"detection"`
	}

	var techniques []Technique
	seen := make(map[string]bool)

	for _, obj := range bundle.Objects {
		if obj.Type != "attack-pattern" {
			continue
		}
		var mitreAttackID string
		for _, r := range obj.ExternalRefs {
			if r.Source == "mitre-attack" {
				mitreAttackID = r.ExternalID
			}
			if r.Source == "mitre-attack" && strings.HasPrefix(r.ExternalID, "T") {
				mitreAttackID = r.ExternalID
			}
		}
		if mitreAttackID == "" || seen[mitreAttackID] {
			continue
		}
		seen[mitreAttackID] = true

		var tactics []string
		for _, kcp := range obj.KillChainPhases {
			tactics = append(tactics, kcp.PhaseName)
		}

		fullTactics := make([]string, 0, len(tactics))
		for _, t := range tactics {
			if name, ok := tacticShort[t]; ok {
				fullTactics = append(fullTactics, name)
			} else {
				fullTactics = append(fullTactics, t)
			}
		}

		var mitigationNames []string
		for _, ref := range obj.ExternalRefs {
			if ref.Source == "mitre-attack" {
				if m, ok := mitigations[ref.ExternalID]; ok {
					mitigationNames = append(mitigationNames, m)
				}
			}
		}

		var detection []string
		if obj.Detection != "" {
			detection = append(detection, obj.Detection)
		}

		techniques = append(techniques, Technique{
			ID:          mitreAttackID,
			Name:        obj.Name,
			Description: obj.Description,
			Tactics:     fullTactics,
			Platforms:   obj.Platforms,
			Mitigations: mitigationNames,
			Detection:   detection,
		})
	}

	jsonData, _ := json.Marshal(techniques)
	escaped := strings.ReplaceAll(string(jsonData), "`", "` + \"`\" + `")
	var buf strings.Builder
	buf.WriteString("package archive\n\n")
	buf.WriteString("// Code generated by tools/wazuh-converter. DO NOT EDIT.\n")
	buf.WriteString("var mitreSeedJSON = `")
	buf.WriteString(escaped)
	buf.WriteString("`\n")

	os.WriteFile(outputPath, []byte(buf.String()), 0644)
	fmt.Printf("Converted %d MITRE techniques to %s\n", len(techniques), outputPath)
}

func convertRootkits() {
	rootcheckDir := `C:\Users\YMA\AppData\Local\Temp\wazuh-rules\ruleset\rootcheck\db`
	outputPath := `D:\Projects_And_Learning\AI\Trace\dev\internal\sift\rootkit_gen.go`

	type rootkitEntry struct {
		Pattern string `json:"pattern"`
		Name    string `json:"name"`
		Ref     string `json:"ref"`
	}

	type trojanEntry struct {
		Binary      string `json:"binary"`
		Signature   string `json:"signature"`
		Description string `json:"description"`
	}

	var rootkits []rootkitEntry
	var trojans []trojanEntry

	// Parse rootkit_files.txt
	if data, err := os.ReadFile(filepath.Join(rootcheckDir, "rootkit_files.txt")); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "!", 3)
			if len(parts) >= 2 {
				entry := rootkitEntry{
					Pattern: strings.TrimSpace(parts[0]),
					Name:    strings.TrimSpace(parts[1]),
				}
				if len(parts) >= 3 {
					entry.Ref = strings.TrimSpace(strings.TrimPrefix(parts[2], "::"))
				}
				rootkits = append(rootkits, entry)
			}
		}
	}

	// Parse rootkit_trojans.txt
	if data, err := os.ReadFile(filepath.Join(rootcheckDir, "rootkit_trojans.txt")); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "!", 3)
			if len(parts) >= 3 {
				trojans = append(trojans, trojanEntry{
					Binary:      strings.TrimSpace(parts[0]),
					Signature:   strings.TrimSpace(parts[1]),
					Description: strings.TrimSpace(parts[2]),
				})
			}
		}
	}

	rkJSON, _ := json.Marshal(rootkits)
	tjJSON, _ := json.Marshal(trojans)

	escRK := strings.ReplaceAll(string(rkJSON), "`", "` + \"`\" + `")
	escTJ := strings.ReplaceAll(string(tjJSON), "`", "` + \"`\" + `")

	var buf strings.Builder
	buf.WriteString("package sift\n\n")
	buf.WriteString("// Code generated by tools/wazuh-converter. DO NOT EDIT.\n\n")
	buf.WriteString("var rootkitFilesJSON = `")
	buf.WriteString(escRK)
	buf.WriteString("`\n\n")
	buf.WriteString("var rootkitTrojanJSON = `")
	buf.WriteString(escTJ)
	buf.WriteString("`\n")

	os.WriteFile(outputPath, []byte(buf.String()), 0644)
	fmt.Printf("Converted %d rootkit files and %d trojan signatures\n", len(rootkits), len(trojans))
}

func convertSCA() {
	scaDir := `C:\Users\YMA\AppData\Local\Temp\wazuh-rules\ruleset\sca`
	outputPath := `D:\Projects_And_Learning\AI\Trace\dev\internal\plugins\sca\policies_gen.go`

	type policyEntry struct {
		ID   string `json:"id"`
		Name string `json:"name"`
		Data string `json:"data"`
	}

	var policies []policyEntry

	filepath.Walk(scaDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(info.Name(), ".yml") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}

		rel, _ := filepath.Rel(scaDir, path)
		id := strings.TrimSuffix(filepath.Base(path), ".yml")
		name := strings.TrimSuffix(rel, ".yml")

		escaped := strings.ReplaceAll(string(data), "`", "` + \"`\" + `")
		policies = append(policies, policyEntry{ID: id, Name: name, Data: escaped})
		return nil
	})

	jsonData, _ := json.Marshal(policies)
	escaped := strings.ReplaceAll(string(jsonData), "`", "` + \"`\" + `")

	var buf strings.Builder
	buf.WriteString("package sca\n\n")
	buf.WriteString("// Code generated by tools/wazuh-converter. DO NOT EDIT.\n\n")
	buf.WriteString("var policiesJSON = `")
	buf.WriteString(escaped)
	buf.WriteString("`\n")

	os.WriteFile(outputPath, []byte(buf.String()), 0644)
	fmt.Printf("Converted %d SCA policies to %s\n", len(policies), outputPath)
}

type WazuhRule struct {
	XMLName     xml.Name `xml:"rule"`
	ID          string   `xml:"id,attr"`
	Level       string   `xml:"level,attr"`
	Frequency   string   `xml:"frequency,attr"`
	Timeframe   string   `xml:"timeframe,attr"`
	NoAlert     string   `xml:"noalert,attr"`
	Match       string   `xml:"match"`
	Regex       string   `xml:"regex"`
	Description string   `xml:"description"`
	Group       string   `xml:"group"`
	IfSID       string   `xml:"if_sid"`
	IfMatchedSID string  `xml:"if_matched_sid"`
	SameSourceIP string  `xml:"same_source_ip"`
	SameUser    string   `xml:"same_user"`
	SameLocation string  `xml:"same_location"`
	Mitre       struct {
		IDs []string `xml:"id"`
	} `xml:"mitre"`
	DecodedAs string `xml:"decoded_as"`
	Field     string `xml:"field"`
}

type WazuhGroup struct {
	XMLName xml.Name    `xml:"group"`
	Name    string      `xml:"name,attr"`
	Rules   []WazuhRule `xml:"rule"`
}

type OutputRule struct {
	RuleID      string            `yaml:"rule_id"`
	Description string            `yaml:"description"`
	Severity    int               `yaml:"severity"`
	MITRE       string            `yaml:"mitre,omitempty"`
	Condition   string            `yaml:"condition"`
	WindowDur   string            `yaml:"window,omitempty"`
	Threshold   int               `yaml:"threshold,omitempty"`
	Playbook    string            `yaml:"playbook,omitempty"`
	PlaybookParams map[string]string `yaml:"params,omitempty"`
}

func mapPlaybook(mitreIDs string, severity int, desc string) (string, map[string]string) {
	mitreList := strings.Split(mitreIDs, ",")
	for _, m := range mitreList {
		m = strings.TrimSpace(m)
		switch m {
		case "T1110", "T1110.001", "T1110.002", "T1110.003", "T1110.004":
			return "ip-reputation", map[string]string{"ip": "${source_ip}"}
		case "T1190", "T1133":
			return "ip-reputation", map[string]string{"ip": "${source_ip}"}
		case "T1204", "T1204.002":
			return "file-analysis", map[string]string{"path": "${file_path}"}
		case "T1566", "T1566.001", "T1566.002", "T1566.003":
			return "email-analysis", map[string]string{"sender_ip": "${source_ip}", "subject": "${subject}"}
		case "T1059", "T1059.001", "T1059.003", "T1059.005", "T1059.006", "T1059.007":
			return "log-analysis", map[string]string{"event_id": "${event_id}"}
		case "T1547", "T1547.001":
			return "registry-check", map[string]string{"registry_key": "${registry_key}"}
		case "T1543", "T1543.003":
			return "file-analysis", map[string]string{"path": "${file_path}"}
		case "T1053", "T1053.005":
			return "file-analysis", map[string]string{"path": "${file_path}"}
		case "T1003":
			return "file-analysis", map[string]string{"hash": "${hash}"}
		case "T1021", "T1021.001", "T1021.002":
			return "ip-reputation", map[string]string{"ip": "${source_ip}"}
		case "T1071", "T1071.001":
			return "domain-reputation", map[string]string{"domain": "${domain}"}
		case "T1562", "T1562.001":
			return "file-analysis", map[string]string{"path": "${file_path}"}
		case "T1078", "T1078.003":
			return "ip-reputation", map[string]string{"ip": "${source_ip}"}
		}
	}

	descLower := strings.ToLower(desc)
	switch {
	case strings.Contains(descLower, "ssh") && strings.Contains(descLower, "brute"):
		return "ip-reputation", map[string]string{"ip": "${source_ip}"}
	case strings.Contains(descLower, "mail") && strings.Contains(descLower, "virus"):
		return "email-analysis", map[string]string{}
	case strings.Contains(descLower, "rootkit"):
		return "rootkit-scan", map[string]string{}
	case strings.Contains(descLower, "compliance") || strings.Contains(descLower, "cis "):
		return "compliance-scan", map[string]string{}
	case strings.Contains(descLower, "malware") || strings.Contains(descLower, "virus"):
		return "file-analysis", map[string]string{}
	case strings.Contains(descLower, "firewall") || strings.Contains(descLower, "blocked"):
		return "ip-reputation", map[string]string{"ip": "${source_ip}"}
	case severity >= 10:
		return "full-enrich", map[string]string{"indicator": "${srcip}"}
	}

	if severity >= 8 {
		return "full-enrich", map[string]string{"indicator": "${srcip}"}
	}
	return "", nil
}

var severityNames = map[int]string{
	0:  "disabled",
	1:  "info",
	2:  "low",
	3:  "low",
	4:  "medium",
	5:  "medium",
	6:  "medium",
	7:  "high",
	8:  "high",
	9:  "critical",
	10: "critical",
	12: "critical",
	13: "critical",
	14: "critical",
	15: "critical",
}

func convertRule(r WazuhRule) *OutputRule {
	if r.NoAlert == "1" || r.Level == "0" {
		return nil
	}

	level, _ := strconv.Atoi(r.Level)
	if level < 3 {
		return nil
	}

	if r.Match == "" && r.Regex == "" {
		return nil
	}

	if r.IfSID != "" && r.Match == "" && r.Regex == "" && r.Frequency == "" {
		return nil
	}

	condition := ""
	val := r.Match
	if val == "" {
		val = r.Regex
	}
	if val != "" {
		val = strings.ReplaceAll(val, `\`, `\\`)
		val = strings.ReplaceAll(val, `"`, `\"`)

		if strings.HasPrefix(val, `^`) {
			condition = `field:message ~= ` + val
		} else if r.Match != "" {
			condition = `field:message ~= (?i)` + regexp.QuoteMeta(r.Match)
		} else {
			condition = `field:message ~= ` + val
		}
	}

	if r.DecodedAs != "" {
		condition = "tag:" + r.DecodedAs
		if val != "" {
		}
	}

	windowDur := ""
	threshold := 0
	if r.Frequency != "" {
		threshold, _ = strconv.Atoi(r.Frequency)
		if threshold < 2 {
			threshold = 2
		}
	}
	if r.Timeframe != "" {
		tf := strings.TrimSuffix(r.Timeframe, "s")
		if secs, err := strconv.Atoi(tf); err == nil {
			windowDur = fmt.Sprintf("%d * time.Second", secs)
		} else {
			windowDur = r.Timeframe + " * time.Second"
		}
	}
	if threshold > 0 && windowDur == "" {
		windowDur = "3600 * time.Second"
	}

	mitreIDs := ""
	if len(r.Mitre.IDs) > 0 {
		mitreIDs = strings.Join(r.Mitre.IDs, ",")
	}

	desc := strings.TrimSpace(r.Description)
	if desc == "" {
		desc = "Wazuh rule " + r.ID
	}

	pb, pbParams := mapPlaybook(mitreIDs, level, desc)

	return &OutputRule{
		RuleID:      "WAZUH_" + r.ID,
		Description: desc,
		Severity:    level,
		MITRE:       mitreIDs,
		Condition:   condition,
		WindowDur:   windowDur,
		Threshold:   threshold,
		Playbook:    pb,
		PlaybookParams: pbParams,
	}
}

func main() {
	rulesDir := `C:\Users\YMA\AppData\Local\Temp\wazuh-rules\ruleset\rules`
	outputDir := `D:\Projects_And_Learning\AI\Trace\dev\internal\siem`

	os.MkdirAll(outputDir, 0755)

	type namedRules struct {
		name  string
		rules []OutputRule
	}

	var allRuleSets []namedRules
	totalConverted := 0
	totalSkipped := 0

	files, _ := os.ReadDir(rulesDir)
	for _, f := range files {
		if filepath.Ext(f.Name()) != ".xml" {
			continue
		}

		data, err := os.ReadFile(filepath.Join(rulesDir, f.Name()))
		if err != nil {
			continue
		}

		content := string(data)

		if !strings.Contains(content, "<group ") && !strings.Contains(content, "<rule ") {
			continue
		}

		var group WazuhGroup
		if err := xml.Unmarshal(data, &group); err != nil {
			var single WazuhRule
			if err := xml.Unmarshal(data, &single); err != nil {
				continue
			}
			group.Rules = []WazuhRule{single}
		}

		var converted []OutputRule
		for _, rule := range group.Rules {
			out := convertRule(rule)
			if out != nil {
				converted = append(converted, *out)
				totalConverted++
			} else {
				totalSkipped++
			}
		}

		if len(converted) > 0 {
			allRuleSets = append(allRuleSets, namedRules{name: f.Name(), rules: converted})
		}
	}

	sort.Slice(allRuleSets, func(i, j int) bool {
		return allRuleSets[i].name < allRuleSets[j].name
	})

	fmt.Printf("Total Wazuh rules parsed: %d\n", totalConverted+totalSkipped)
	fmt.Printf("Converted: %d\n", totalConverted)
	fmt.Printf("Skipped (low/no match/no alert): %d\n", totalSkipped)
	fmt.Printf("Rule sets: %d\n", len(allRuleSets))

	var goBuf strings.Builder
	goBuf.WriteString("package siem\n\n")
	goBuf.WriteString("import \"time\"\n\n")
	goBuf.WriteString("func loadWazuhRules() []CompiledRule {\n")
	goBuf.WriteString("\treturn []CompiledRule{\n")

	ruleCount := 0
	for _, rs := range allRuleSets {
		for _, r := range rs.rules {
			ruleCount++
			goBuf.WriteString(fmt.Sprintf("\t\t{\n"))
			goBuf.WriteString(fmt.Sprintf("\t\t\tRuleID:      %q,\n", r.RuleID))
			goBuf.WriteString(fmt.Sprintf("\t\t\tDescription: %q,\n", r.Description))
			goBuf.WriteString(fmt.Sprintf("\t\t\tSeverity:    %d,\n", r.Severity))

			if r.MITRE != "" {
				goBuf.WriteString(fmt.Sprintf("\t\t\tMITRE:       %q,\n", r.MITRE))
			}

			cond := r.Condition
			cond = strings.ReplaceAll(cond, `\\`, `\`)
			cond = strings.ReplaceAll(cond, `\"`, `"`)
			if cond != "" {
				goBuf.WriteString(fmt.Sprintf("\t\t\tcondition:   %q,\n", cond))
			}

			if r.Threshold > 0 {
				goBuf.WriteString(fmt.Sprintf("\t\t\tthreshold:   %d,\n", r.Threshold))
			}
			if r.WindowDur != "" {
				goBuf.WriteString(fmt.Sprintf("\t\t\twindowDur:   %s,\n", r.WindowDur))
			}

			if r.Playbook != "" {
				goBuf.WriteString(fmt.Sprintf("\t\t\tActions:     []RuleAction{{Playbook: %q, Params: map[string]any{", r.Playbook))
				first := true
				for k, v := range r.PlaybookParams {
					if !first {
						goBuf.WriteString(", ")
					}
					goBuf.WriteString(fmt.Sprintf("%q: %q", k, v))
					first = false
				}
				goBuf.WriteString("}}},\n")
			}

			goBuf.WriteString("\t\t},\n")
		}
	}

	goBuf.WriteString("\t}\n")
	goBuf.WriteString("}\n")

	outPath := filepath.Join(outputDir, "wazuh_rules_gen.go")
	if err := os.WriteFile(outPath, []byte(goBuf.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nGenerated %s with %d rules\n", outPath, ruleCount)

	convertDecoders()
	convertLists()
	convertMitre()
	convertRootkits()
	convertSCA()
}
